// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

import (
	"time"

	"github.com/beneath-core/beneath-go/control/entity"
)

type Me struct {
	UserID    string      `json:"userID"`
	User      *entity.User `json:"user"`
	Email     string      `json:"email"`
	UpdatedOn time.Time   `json:"updatedOn"`
}

type NewSecret struct {
	Secret       *entity.Secret `json:"secret"`
	SecretString string        `json:"secretString"`
}
