const FREE_BILLING_PLAN_DESCRIPTION = "Free"
const PRO_BILLING_PLAN_DESCRIPTION = "Professional"

const MONTHLY_BILLING_PLAN_STRING = "Monthly"

const FREE_BILLING_PLAN_ID = "9f9c375e-3390-48ac-8de1-c0fe2c5efdfb"
const PRO_MONTHLY_BILLING_PLAN_ID = "cb3106b6-52f0-44e3-941d-73406abf4b3a"

const ANARCHISM_DRIVER = "anarchism"
const STRIPECARD_DRIVER = "stripecard"
const STRIPEWIRE_DRIVER = "stripewire"

const STRIPE_KEY = "pk_test_L140lbWnkGmtqSiw8rH2wcNs00otQFgbbr"

module.exports = {
  FREE_BILLING_PLAN_DESCRIPTION,
  PRO_BILLING_PLAN_DESCRIPTION,
  FREE_BILLING_PLAN_ID,
  MONTHLY_BILLING_PLAN_STRING,
  PRO_MONTHLY_BILLING_PLAN_ID,
  ANARCHISM_DRIVER,
  STRIPECARD_DRIVER,
  STRIPEWIRE_DRIVER,
  STRIPE_KEY
};
