module.exports = {
  ANARCHISM_DRIVER,
  STRIPECARD_DRIVER,
  STRIPEWIRE_DRIVER,
  STRIPE_KEY,
  COUNTRIES,
  US_STATES
};

const ANARCHISM_DRIVER = "anarchism"
const STRIPECARD_DRIVER = "stripecard"
const STRIPEWIRE_DRIVER = "stripewire"

const STRIPE_KEY = "pk_test_L140lbWnkGmtqSiw8rH2wcNs00otQFgbbr"

const COUNTRIES = [
  { name: 'Afghanistan', label: 'Afghanistan', code: 'AF' },
  { name: 'Åland Islands', label: 'Åland Islands', code: 'AX'},
  { name: 'Albania', label: 'Albania', code: 'AL' },
  { name: 'Algeria', label: 'Algeria', code: 'DZ'},
  { name: 'American Samoa', label: 'American Samoa', code: 'AS' },
  { name: 'Andorra', label: 'Andorra', code: 'AD'},
  { name: 'Angola', label: 'Angola', code: 'AO' },
  { name: 'Anguilla', label: 'Anguilla', code: 'AI' },
  { name: 'Antarctica', label: 'Antarctica', code: 'AQ' },
  { name: 'Antigua and Barbuda', label: 'Antigua and Barbuda', code: 'AG' },
  { name: 'Argentina', label: 'Argentina', code: 'AR' },
  { name: 'Armenia', label: 'Armenia', code: 'AM' },
  { name: 'Aruba', label: 'Aruba', code: 'AW' },
  { name: 'Australia', label: 'Australia', code: 'AU' },
  { name: 'Austria', label: 'Austria', code: 'AT' },
  { name: 'Azerbaijan', label: 'Azerbaijan', code: 'AZ' },
  { name: 'Bahamas', label: 'Bahamas', code: 'BS' },
  { name: 'Bahrain', label: 'Bahrain', code: 'BH' },
  { name: 'Bangladesh', label: 'Bangladesh', code: 'BD' },
  { name: 'Barbados', label: 'Barbados', code: 'BB' },
  { name: 'Belarus', label: 'Belarus', code: 'BY' },
  { name: 'Belgium', label: 'Belgium', code: 'BE' },
  { name: 'Belize', label: 'Belize', code: 'BZ' },
  { name: 'Benin', label: 'Benin', code: 'BJ' },
  { name: 'Bermuda', label: 'Bermuda', code: 'BM' },
  { name: 'Bhutan', label: 'Bhutan', code: 'BT' },
  { name: 'Bolivia', label: 'Bolivia', code: 'BO' },
  { name: 'Bonaire, Sint Eustatius and Saba', label: 'Bonaire, Sint Eustatius and Saba', code: 'BQ' },
  { name: 'Bosnia and Herzegovina', label: 'Bosnia and Herzegovina', code: 'BA' },
  { name: 'Botswana', label: 'Botswana', code: 'BW' },
  { name: 'Bouvet Island', label: 'Bouvet Island', code: 'BV' },
  { name: 'Brazil', label: 'Brazil', code: 'BR' },
  { name: 'British Indian Ocean Territory', label: 'British Indian Ocean Territory', code: 'IO' },
  { name: 'Brunei Darussalam', label: 'Brunei Darussalam', code: 'BN' },
  { name: 'Bulgaria', label: 'Bulgaria', code: 'BG' },
  { name: 'Burkina Faso', label: 'Burkina Faso', code: 'BF' },
  { name: 'Burundi', label: 'Burundi', code: 'BI' },
  { name: 'Cabo Verde', label: 'Cabo Verde', code: 'CV' },
  { name: 'Cambodia', label: 'Cambodia', code: 'KH' },
  { name: 'Cameroon', label: 'Cameroon', code: 'CM' },
  { name: 'Canada', label: 'Canada', code: 'CA' },
  { name: 'Cayman Islands', label: 'Cayman Islands', code: 'KY' },
  { name: 'Central African Republic', label: 'Central African Republic', code: 'CF' },
  { name: 'Chad', label: 'Chad', code: 'TD' },
  { name: 'Chile', label: 'Chile', code: 'CL' },
  { name: 'China', label: 'China', code: 'CN' },
  { name: 'Christmas Island', label: 'Christmas Island', code: 'CX' },
  { name: 'Cocos (Keeling) Islands', label: 'Cocos (Keeling) Islands', code: 'CC' },
  { name: 'Colombia', label: 'Colombia', code: 'CO' },
  { name: 'Comoros', label: 'Comoros', code: 'KM' },
  { name: 'Congo', label: 'Congo', code: 'CG' },
  { name: 'Congo, Democratic Republic of the', label: 'Congo, Democratic Republic of the', code: 'CD' },
  { name: 'Cook Islands', label: 'Cook Islands', code: 'CK' },
  { name: 'Costa Rica', label: 'Costa Rica', code: 'CR' },
  { name: "Côte d'Ivoire", label: "Côte d'Ivoire", code: 'CI' },
  { name: 'Croatia', label: 'Croatia', code: 'HR' },
  { name: 'Cuba', label: 'Cuba', code: 'CU' },
  { name: 'Curaçao', label: 'Curaçao', code: 'CW' },
  { name: 'Cyprus', label: 'Cyprus', code: 'CY' },
  { name: 'Czechia', label: 'Czechia', code: 'CZ' },
  { name: 'Denmark', label: 'Denmark', code: 'DK' },
  { name: 'Djibouti', label: 'Djibouti', code: 'DJ' },
  { name: 'Dominica', label: 'Dominica', code: 'DM' },
  { name: 'Dominican Republic', label: 'Dominican Republic', code: 'DO' },
  { name: 'Ecuador', label: 'Ecuador', code: 'EC' },
  { name: 'Egypt', label: 'Egypt', code: 'EG' },
  { name: 'El Salvador', label: 'El Salvador', code: 'SV' },
  { name: 'Equatorial Guinea', label: 'Equatorial Guinea', code: 'GQ' },
  { name: 'Eritrea', label: 'Eritrea', code: 'ER' },
  { name: 'Estonia', label: 'Estonia', code: 'EE' },
  { name: 'Eswatini', label: 'Eswatini', code: 'SZ' },
  { name: 'Ethiopia', label: 'Ethiopia', code: 'ET' },
  { name: 'Falkland Islands', label: 'Falkland Islands', code: 'FK' },
  { name: 'Faroe Islands', label: 'Faroe Islands', code: 'FO' },
  { name: 'Fiji', label: 'Fiji', code: 'FJ' },
  { name: 'Finland', label: 'Finland', code: 'FI' },
  { name: 'France', label: 'France', code: 'FR' },
  { name: 'French Guiana', label: 'French Guiana', code: 'GF' },
  { name: 'French Polynesia', label: 'French Polynesia', code: 'PF' },
  { name: 'French Southern Territories', label: 'French Southern Territories', code: 'TF' },
  { name: 'Gabon', label: 'Gabon', code: 'GA' },
  { name: 'Gambia', label: 'Gambia', code: 'GM' },
  { name: 'Georgia', label: 'Georgia', code: 'GE' },
  { name: 'Germany', label: 'Germany', code: 'DE' },
  { name: 'Ghana', label: 'Ghana', code: 'GH' },
  { name: 'Gibraltar', label: 'Gibraltar', code: 'GI' },
  { name: 'Greece', label: 'Greece', code: 'GR' },
  { name: 'Greenland', label: 'Greenland', code: 'GL' },
  { name: 'Grenada', label: 'Grenada', code: 'GD' },
  { name: 'Guadeloupe', label: 'Guadeloupe', code: 'GP' },
  { name: 'Guam', label: 'Guam', code: 'GU' },
  { name: 'Guatemala', label: 'Guatemala', code: 'GT' },
  { name: 'Guernsey', label: 'Guernsey', code: 'GG' },
  { name: 'Guinea', label: 'Guinea', code: 'GN' },
  { name: 'Guinea-Bissau', label: 'Guinea-Bissau', code: 'GW' },
  { name: 'Guyana', label: 'Guyana', code: 'GY' },
  { name: 'Haiti', label: 'Haiti', code: 'HT' },
  { name: 'Heard Island and McDonald Islands', label: 'Heard Island and McDonald Islands', code: 'HM' },
  { name: 'Holy See', label: 'Holy See', code: 'VA' },
  { name: 'Honduras', label: 'Honduras', code: 'HN' },
  { name: 'Hong Kong', label: 'Hong Kong', code: 'HK' },
  { name: 'Hungary', label: 'Hungary', code: 'HU' },
  { name: 'Iceland', label: 'Iceland', code: 'IS' },
  { name: 'India', label: 'India', code: 'IN' },
  { name: 'Indonesia', label: 'Indonesia', code: 'ID' },
  { name: 'Iran', label: 'Iran', code: 'IR' },
  { name: 'Iraq', label: 'Iraq', code: 'IQ' },
  { name: 'Ireland', label: 'Ireland', code: 'IE' },
  { name: 'Isle of Man', label: 'Isle of Man', code: 'IM' },
  { name: 'Israel', label: 'Israel', code: 'IL' },
  { name: 'Italy', label: 'Italy', code: 'IT' },
  { name: 'Jamaica', label: 'Jamaica', code: 'JM' },
  { name: 'Japan', label: 'Japan', code: 'JP' },
  { name: 'Jersey', label: 'Jersey', code: 'JE' },
  { name: 'Jordan', label: 'Jordan', code: 'JO' },
  { name: 'Kazakhstan', label: 'Kazakhstan', code: 'KZ' },
  { name: 'Kenya', label: 'Kenya', code: 'KE' },
  { name: 'Kiribati', label: 'Kiribati', code: 'KI' },
  { name: 'North Korea', label: 'North Korea', code: 'KP' },
  { name: 'South Korea', label: 'South Korea', code: 'KR' },
  { name: 'Kuwait', label: 'Kuwait', code: 'KW' },
  { name: 'Kyrgyzstan', label: 'Kyrgyzstan', code: 'KG' },
  { name: "Lao People's Democratic Republic", label: "Lao People's Democratic Republic", code: 'LA' },
  { name: 'Latvia', label: 'Latvia', code: 'LV' },
  { name: 'Lebanon', label: 'Lebanon', code: 'LB' },
  { name: 'Lesotho', label: 'Lesotho', code: 'LS' },
  { name: 'Liberia', label: 'Liberia', code: 'LR' },
  { name: 'Libya', label: 'Libya', code: 'LY' },
  { name: 'Liechtenstein', label: 'Liechtenstein', code: 'LI' },
  { name: 'Lithuania', label: 'Lithuania', code: 'LT' },
  { name: 'Luxembourg', label: 'Luxembourg', code: 'LU' },
  { name: 'Macao', label: 'Macao', code: 'MO' },
  { name: 'Madagascar', label: 'Madagascar', code: 'MG' },
  { name: 'Malawi', label: 'Malawi', code: 'MW' },
  { name: 'Malaysia', label: 'Malaysia', code: 'MY' },
  { name: 'Maldives', label: 'Maldives', code: 'MV' },
  { name: 'Mali', label: 'Mali', code: 'ML' },
  { name: 'Malta', label: 'Malta', code: 'MT' },
  { name: 'Marshall Islands', label: 'Marshall Islands', code: 'MH' },
  { name: 'Martinique', label: 'Martinique', code: 'MQ' },
  { name: 'Mauritania', label: 'Mauritania', code: 'MR' },
  { name: 'Mauritius', label: 'Mauritius', code: 'MU' },
  { name: 'Mayotte', label: 'Mayotte', code: 'YT' },
  { name: 'Mexico', label: 'Mexico', code: 'MX' },
  { name: 'Micronesia (Federated States of)', label: 'Micronesia (Federated States of)', code: 'FM' },
  { name: 'Moldova, Republic of', label: 'Moldova, Republic of', code: 'MD' },
  { name: 'Monaco', label: 'Monaco', code: 'MC' },
  { name: 'Mongolia', label: 'Mongolia', code: 'MN' },
  { name: 'Montenegro', label: 'Montenegro', code: 'ME' },
  { name: 'Montserrat', label: 'Montserrat', code: 'MS' },
  { name: 'Morocco', label: 'Morocco', code: 'MA' },
  { name: 'Mozambique', label: 'Mozambique', code: 'MZ' },
  { name: 'Myanmar', label: 'Myanmar', code: 'MM' },
  { name: 'Namibia', label: 'Namibia', code: 'NA' },
  { name: 'Nauru', label: 'Nauru', code: 'NR' },
  { name: 'Nepal', label: 'Nepal', code: 'NP' },
  { name: 'Netherlands', label: 'Netherlands', code: 'NL' },
  { name: 'New Caledonia', label: 'New Caledonia', code: 'NC' },
  { name: 'New Zealand', label: 'New Zealand', code: 'NZ' },
  { name: 'Nicaragua', label: 'Nicaragua', code: 'NI' },
  { name: 'Niger', label: 'Niger', code: 'NE' },
  { name: 'Nigeria', label: 'Nigeria', code: 'NG' },
  { name: 'Niue', label: 'Niue', code: 'NU' },
  { name: 'Norfolk Island', label: 'Norfolk Island', code: 'NF' },
  { name: 'North Macedonia', label: 'North Macedonia', code: 'MK' },
  { name: 'Northern Mariana Islands', label: 'Northern Mariana Islands', code: 'MP' },
  { name: 'Norway', label: 'Norway', code: 'NO' },
  { name: 'Oman', label: 'Oman', code: 'OM' },
  { name: 'Pakistan', label: 'Pakistan', code: 'PK' },
  { name: 'Palau', label: 'Palau', code: 'PW' },
  { name: 'Palestine, State of', label: 'Palestine, State of', code: 'PS' },
  { name: 'Panama', label: 'Panama', code: 'PA' },
  { name: 'Papua New Guinea', label: 'Papua New Guinea', code: 'PG' },
  { name: 'Paraguay', label: 'Paraguay', code: 'PY' },
  { name: 'Peru', label: 'Peru', code: 'PE' },
  { name: 'Philippines', label: 'Philippines', code: 'PH' },
  { name: 'Pitcairn', label: 'Pitcairn', code: 'PN' },
  { name: 'Poland', label: 'Poland', code: 'PL' },
  { name: 'Portugal', label: 'Portugal', code: 'PT' },
  { name: 'Puerto Rico', label: 'Puerto Rico', code: 'PR' },
  { name: 'Qatar', label: 'Qatar', code: 'QA' },
  { name: 'Réunion', label: 'Réunion', code: 'RE' },
  { name: 'Romania', label: 'Romania', code: 'RO' },
  { name: 'Russian Federation', label: 'Russian Federation', code: 'RU' },
  { name: 'Rwanda', label: 'Rwanda', code: 'RW' },
  { name: 'Saint Barthélemy', label: 'Saint Barthélemy', code: 'BL' },
  { name: 'Saint Helena, Ascension and Tristan da Cunha', label: 'Saint Helena, Ascension and Tristan da Cunha', code: 'SH' },
  { name: 'Saint Kitts and Nevis', label: 'Saint Kitts and Nevis', code: 'KN' },
  { name: 'Saint Lucia', label: 'Saint Lucia', code: 'LC' },
  { name: 'Saint Martin (French part)', label: 'Saint Martin (French part)', code: 'MF' },
  { name: 'Saint Pierre and Miquelon', label: 'Saint Pierre and Miquelon', code: 'PM' },
  { name: 'Saint Vincent and the Grenadines', label: 'Saint Vincent and the Grenadines', code: 'VC' },
  { name: 'Samoa', label: 'Samoa', code: 'WS' },
  { name: 'San Marino', label: 'San Marino', code: 'SM' },
  { name: 'Sao Tome and Principe', label: 'Sao Tome and Principe', code: 'ST' },
  { name: 'Saudi Arabia', label: 'Saudi Arabia', code: 'SA' },
  { name: 'Senegal', label: 'Senegal', code: 'SN' },
  { name: 'Serbia', label: 'Serbia', code: 'RS' },
  { name: 'Seychelles', label: 'Seychelles', code: 'SC' },
  { name: 'Sierra Leone', label: 'Sierra Leone', code: 'SL' },
  { name: 'Singapore', label: 'Singapore', code: 'SG' },
  { name: 'Sint Maarten (Dutch part)', label: 'Sint Maarten (Dutch part)', code: 'SX' },
  { name: 'Slovakia', label: 'Slovakia', code: 'SK' },
  { name: 'Slovenia', label: 'Slovenia', code: 'SI' },
  { name: 'Solomon Islands', label: 'Solomon Islands', code: 'SB' },
  { name: 'Somalia', label: 'Somalia', code: 'SO' },
  { name: 'South Africa', label: 'South Africa', code: 'ZA' },
  { name: 'South Georgia and the South Sandwich Islands', label: 'South Georgia and the South Sandwich Islands', code: 'GS' },
  { name: 'South Sudan', label: 'South Sudan', code: 'SS' },
  { name: 'Spain', label: 'Spain', code: 'ES' },
  { name: 'Sri Lanka', label: 'Sri Lanka', code: 'LK' },
  { name: 'Sudan', label: 'Sudan', code: 'SD' },
  { name: 'Suriname', label: 'Suriname', code: 'SR' },
  { name: 'Svalbard and Jan Mayen', label: 'Svalbard and Jan Mayen', code: 'SJ' },
  { name: 'Sweden', label: 'Sweden', code: 'SE' },
  { name: 'Switzerland', label: 'Switzerland', code: 'CH' },
  { name: 'Syrian Arab Republic', label: 'Syrian Arab Republic', code: 'SY' },
  { name: 'Taiwan, Province of China', label: 'Taiwan, Province of China', code: 'TW' },
  { name: 'Tajikistan', label: 'Tajikistan', code: 'TJ' },
  { name: 'Tanzania, United Republic of', label: 'Tanzania, United Republic of', code: 'TZ' },
  { name: 'Thailand', label: 'Thailand', code: 'TH' },
  { name: 'Timor-Leste', label: 'Timor-Leste', code: 'TL' },
  { name: 'Togo', label: 'Togo', code: 'TG' },
  { name: 'Tokelau', label: 'Tokelau', code: 'TK' },
  { name: 'Tonga', label: 'Tonga', code: 'TO' },
  { name: 'Trinidad and Tobago', label: 'Trinidad and Tobago', code: 'TT' },
  { name: 'Tunisia', label: 'Tunisia', code: 'TN' },
  { name: 'Turkey', label: 'Turkey', code: 'TR' },
  { name: 'Turkmenistan', label: 'Turkmenistan', code: 'TM' },
  { name: 'Turks and Caicos Islands', label: 'Turks and Caicos Islands', code: 'TC' },
  { name: 'Tuvalu', label: 'Tuvalu', code: 'TV' },
  { name: 'Uganda', label: 'Uganda', code: 'UG' },
  { name: 'Ukraine', label: 'Ukraine', code: 'UA' },
  { name: 'United Arab Emirates', label: 'United Arab Emirates', code: 'AE' },
  { name: 'United Kingdom of Great Britain and Northern Ireland', label: 'United Kingdom of Great Britain and Northern Ireland', code: 'GB' },
  { name: 'United States Minor Outlying Islands', label: 'United States Minor Outlying Islands', code: 'UM' },
  { name: 'United States of America', label: 'United States of America', code: 'US' },
  { name: 'Uruguay', label: 'Uruguay', code: 'UY' },
  { name: 'Uzbekistan', label: 'Uzbekistan', code: 'UZ' },
  { name: 'Vanuatu', label: 'Vanuatu', code: 'VU' },
  { name: 'Venezuela (Bolivarian Republic of)', label: 'Venezuela (Bolivarian Republic of)', code: 'VE' },
  { name: 'Viet Nam', label: 'Viet Nam', code: 'VN' },
  { name: 'Virgin Islands (British)', label: 'Virgin Islands (British)', code: 'VG' },
  { name: 'Virgin Islands (U.S.)', label: 'Virgin Islands (U.S.)', code: 'VI' },
  { name: 'Wallis and Futuna', label: 'Wallis and Futuna', code: 'WF' },
  { name: 'Western Sahara', label: 'Western Sahara', code: 'EH' },
  { name: 'Yemen', label: 'Yemen', code: 'YE' },
  { name: 'Zambia', label: 'Zambia', code: 'ZM' },
  { name: 'Zimbabwe', label: 'Zimbabwe', code: 'ZW' }
]

const US_STATES = [
  { label: 'Alabama', name: 'Alabama' },
  { label: 'Alaska', name: 'Alaska' },
  { label: 'Arizona', name: 'Arizona' },
  { label: 'Arkansas', name: 'Arkansas' },
  { label: 'California', name: 'California' },
  { label: 'Colorado', name: 'Colorado' },
  { label: 'Connecticut', name: 'Connecticut' },
  { label: 'Delaware', name: 'Delaware' },
  { label: 'District of Columbia', name: 'District of Columbia' },
  { label: 'Florida', name: 'Florida' },
  { label: 'Georgia', name: 'Georgia' },
  { label: 'Hawaii', name: 'Hawaii' },
  { label: 'Idaho', name: 'Idaho' },
  { label: 'Illinois', name: 'Illinois' },
  { label: 'Indiana', name: 'Indiana' },
  { label: 'Iowa', name: 'Iowa' },
  { label: 'Kansas', name: 'Kansas' },
  { label: 'Kentucky', name: 'Kentucky' },
  { label: 'Louisiana', name: 'Louisiana' },
  { label: 'Maine', name: 'Maine' },
  { label: 'Maryland', name: 'Maryland' },
  { label: 'Massachusetts', name: 'Massachusetts' },
  { label: 'Michigan', name: 'Michigan' },
  { label: 'Minnesota', name: 'Minnesota' },
  { label: 'Mississippi', name: 'Mississippi' },
  { label: 'Missouri', name: 'Missouri' },
  { label: 'Montana', name: 'Montana' },
  { label: 'Nebraska', name: 'Nebraska' },
  { label: 'Nevada', name: 'Nevada' },
  { label: 'New Hampshire', name: 'New Hampshire' },
  { label: 'New Jersey', name: 'New Jersey' },
  { label: 'New Mexico', name: 'New Mexico' },
  { label: 'New York', name: 'New York' },
  { label: 'North Carolina', name: 'North Carolina' },
  { label: 'North Dakota', name: 'North Dakota' },
  { label: 'Ohio', name: 'Ohio' },
  { label: 'Oklahoma', name: 'Oklahoma' },
  { label: 'Oregon', name: 'Oregon' },
  { label: 'Pennsylvania', name: 'Pennsylvania' },
  { label: 'Puerto Rico', name: 'Puerto Rico' },
  { label: 'Rhode Island', name: 'Rhode Island' },
  { label: 'South Carolina', name: 'South Carolina' },
  { label: 'South Dakota', name: 'South Dakota' },
  { label: 'Tennessee', name: 'Tennessee' },
  { label: 'Texas', name: 'Texas' },
  { label: 'Utah', name: 'Utah' },
  { label: 'Vermont', name: 'Vermont' },
  { label: 'Virginia', name: 'Virginia' },
  { label: 'Washington', name: 'Washington' },
  { label: 'West Virginia', name: 'West Virginia' },
  { label: 'Wisconsin', name: 'Wisconsin' },
  { label: 'Wyoming', name: 'Wyoming' }
]
