// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway/grpc/proto/gateway.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Record struct {
	AvroData             []byte   `protobuf:"bytes,1,opt,name=avro_data,json=avroData,proto3" json:"avro_data,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a2419213bb16, []int{0}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetAvroData() []byte {
	if m != nil {
		return m.AvroData
	}
	return nil
}

func (m *Record) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type InstanceRecords struct {
	InstanceId           []byte    `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Records              []*Record `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *InstanceRecords) Reset()         { *m = InstanceRecords{} }
func (m *InstanceRecords) String() string { return proto.CompactTextString(m) }
func (*InstanceRecords) ProtoMessage()    {}
func (*InstanceRecords) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a2419213bb16, []int{1}
}

func (m *InstanceRecords) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceRecords.Unmarshal(m, b)
}
func (m *InstanceRecords) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceRecords.Marshal(b, m, deterministic)
}
func (m *InstanceRecords) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceRecords.Merge(m, src)
}
func (m *InstanceRecords) XXX_Size() int {
	return xxx_messageInfo_InstanceRecords.Size(m)
}
func (m *InstanceRecords) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceRecords.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceRecords proto.InternalMessageInfo

func (m *InstanceRecords) GetInstanceId() []byte {
	if m != nil {
		return m.InstanceId
	}
	return nil
}

func (m *InstanceRecords) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

type WarehouseJob struct {
	JobId                []byte   `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WarehouseJob) Reset()         { *m = WarehouseJob{} }
func (m *WarehouseJob) String() string { return proto.CompactTextString(m) }
func (*WarehouseJob) ProtoMessage()    {}
func (*WarehouseJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a2419213bb16, []int{2}
}

func (m *WarehouseJob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WarehouseJob.Unmarshal(m, b)
}
func (m *WarehouseJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WarehouseJob.Marshal(b, m, deterministic)
}
func (m *WarehouseJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WarehouseJob.Merge(m, src)
}
func (m *WarehouseJob) XXX_Size() int {
	return xxx_messageInfo_WarehouseJob.Size(m)
}
func (m *WarehouseJob) XXX_DiscardUnknown() {
	xxx_messageInfo_WarehouseJob.DiscardUnknown(m)
}

var xxx_messageInfo_WarehouseJob proto.InternalMessageInfo

func (m *WarehouseJob) GetJobId() []byte {
	if m != nil {
		return m.JobId
	}
	return nil
}

type PingRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientVersion        string   `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a2419213bb16, []int{3}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *PingRequest) GetClientVersion() string {
	if m != nil {
		return m.ClientVersion
	}
	return ""
}

type PingResponse struct {
	Authenticated        bool     `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	VersionStatus        string   `protobuf:"bytes,2,opt,name=version_status,json=versionStatus,proto3" json:"version_status,omitempty"`
	RecommendedVersion   string   `protobuf:"bytes,3,opt,name=recommended_version,json=recommendedVersion,proto3" json:"recommended_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a2419213bb16, []int{4}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetAuthenticated() bool {
	if m != nil {
		return m.Authenticated
	}
	return false
}

func (m *PingResponse) GetVersionStatus() string {
	if m != nil {
		return m.VersionStatus
	}
	return ""
}

func (m *PingResponse) GetRecommendedVersion() string {
	if m != nil {
		return m.RecommendedVersion
	}
	return ""
}

type WriteRequest struct {
	InstanceRecords      []*InstanceRecords `protobuf:"bytes,1,rep,name=instance_records,json=instanceRecords,proto3" json:"instance_records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *WriteRequest) Reset()         { *m = WriteRequest{} }
func (m *WriteRequest) String() string { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()    {}
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a2419213bb16, []int{5}
}

func (m *WriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRequest.Unmarshal(m, b)
}
func (m *WriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRequest.Marshal(b, m, deterministic)
}
func (m *WriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRequest.Merge(m, src)
}
func (m *WriteRequest) XXX_Size() int {
	return xxx_messageInfo_WriteRequest.Size(m)
}
func (m *WriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRequest proto.InternalMessageInfo

func (m *WriteRequest) GetInstanceRecords() []*InstanceRecords {
	if m != nil {
		return m.InstanceRecords
	}
	return nil
}

type WriteResponse struct {
	WriteId              []byte   `protobuf:"bytes,1,opt,name=write_id,json=writeId,proto3" json:"write_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteResponse) Reset()         { *m = WriteResponse{} }
func (m *WriteResponse) String() string { return proto.CompactTextString(m) }
func (*WriteResponse) ProtoMessage()    {}
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a2419213bb16, []int{6}
}

func (m *WriteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteResponse.Unmarshal(m, b)
}
func (m *WriteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteResponse.Marshal(b, m, deterministic)
}
func (m *WriteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteResponse.Merge(m, src)
}
func (m *WriteResponse) XXX_Size() int {
	return xxx_messageInfo_WriteResponse.Size(m)
}
func (m *WriteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WriteResponse proto.InternalMessageInfo

func (m *WriteResponse) GetWriteId() []byte {
	if m != nil {
		return m.WriteId
	}
	return nil
}

type QueryLogRequest struct {
	InstanceId           []byte   `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Partitions           int32    `protobuf:"varint,2,opt,name=partitions,proto3" json:"partitions,omitempty"`
	Peek                 bool     `protobuf:"varint,3,opt,name=peek,proto3" json:"peek,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryLogRequest) Reset()         { *m = QueryLogRequest{} }
func (m *QueryLogRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLogRequest) ProtoMessage()    {}
func (*QueryLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a2419213bb16, []int{7}
}

func (m *QueryLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryLogRequest.Unmarshal(m, b)
}
func (m *QueryLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryLogRequest.Marshal(b, m, deterministic)
}
func (m *QueryLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLogRequest.Merge(m, src)
}
func (m *QueryLogRequest) XXX_Size() int {
	return xxx_messageInfo_QueryLogRequest.Size(m)
}
func (m *QueryLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLogRequest proto.InternalMessageInfo

func (m *QueryLogRequest) GetInstanceId() []byte {
	if m != nil {
		return m.InstanceId
	}
	return nil
}

func (m *QueryLogRequest) GetPartitions() int32 {
	if m != nil {
		return m.Partitions
	}
	return 0
}

func (m *QueryLogRequest) GetPeek() bool {
	if m != nil {
		return m.Peek
	}
	return false
}

type QueryLogResponse struct {
	ReplayCursors        [][]byte `protobuf:"bytes,1,rep,name=replay_cursors,json=replayCursors,proto3" json:"replay_cursors,omitempty"`
	ChangeCursors        [][]byte `protobuf:"bytes,2,rep,name=change_cursors,json=changeCursors,proto3" json:"change_cursors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryLogResponse) Reset()         { *m = QueryLogResponse{} }
func (m *QueryLogResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLogResponse) ProtoMessage()    {}
func (*QueryLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a2419213bb16, []int{8}
}

func (m *QueryLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryLogResponse.Unmarshal(m, b)
}
func (m *QueryLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryLogResponse.Marshal(b, m, deterministic)
}
func (m *QueryLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLogResponse.Merge(m, src)
}
func (m *QueryLogResponse) XXX_Size() int {
	return xxx_messageInfo_QueryLogResponse.Size(m)
}
func (m *QueryLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLogResponse proto.InternalMessageInfo

func (m *QueryLogResponse) GetReplayCursors() [][]byte {
	if m != nil {
		return m.ReplayCursors
	}
	return nil
}

func (m *QueryLogResponse) GetChangeCursors() [][]byte {
	if m != nil {
		return m.ChangeCursors
	}
	return nil
}

type QueryIndexRequest struct {
	InstanceId           []byte   `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Partitions           int32    `protobuf:"varint,2,opt,name=partitions,proto3" json:"partitions,omitempty"`
	Filter               string   `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryIndexRequest) Reset()         { *m = QueryIndexRequest{} }
func (m *QueryIndexRequest) String() string { return proto.CompactTextString(m) }
func (*QueryIndexRequest) ProtoMessage()    {}
func (*QueryIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a2419213bb16, []int{9}
}

func (m *QueryIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryIndexRequest.Unmarshal(m, b)
}
func (m *QueryIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryIndexRequest.Marshal(b, m, deterministic)
}
func (m *QueryIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIndexRequest.Merge(m, src)
}
func (m *QueryIndexRequest) XXX_Size() int {
	return xxx_messageInfo_QueryIndexRequest.Size(m)
}
func (m *QueryIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIndexRequest proto.InternalMessageInfo

func (m *QueryIndexRequest) GetInstanceId() []byte {
	if m != nil {
		return m.InstanceId
	}
	return nil
}

func (m *QueryIndexRequest) GetPartitions() int32 {
	if m != nil {
		return m.Partitions
	}
	return 0
}

func (m *QueryIndexRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

type QueryIndexResponse struct {
	ReplayCursors        [][]byte `protobuf:"bytes,1,rep,name=replay_cursors,json=replayCursors,proto3" json:"replay_cursors,omitempty"`
	ChangeCursors        [][]byte `protobuf:"bytes,2,rep,name=change_cursors,json=changeCursors,proto3" json:"change_cursors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryIndexResponse) Reset()         { *m = QueryIndexResponse{} }
func (m *QueryIndexResponse) String() string { return proto.CompactTextString(m) }
func (*QueryIndexResponse) ProtoMessage()    {}
func (*QueryIndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a2419213bb16, []int{10}
}

func (m *QueryIndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryIndexResponse.Unmarshal(m, b)
}
func (m *QueryIndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryIndexResponse.Marshal(b, m, deterministic)
}
func (m *QueryIndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIndexResponse.Merge(m, src)
}
func (m *QueryIndexResponse) XXX_Size() int {
	return xxx_messageInfo_QueryIndexResponse.Size(m)
}
func (m *QueryIndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIndexResponse proto.InternalMessageInfo

func (m *QueryIndexResponse) GetReplayCursors() [][]byte {
	if m != nil {
		return m.ReplayCursors
	}
	return nil
}

func (m *QueryIndexResponse) GetChangeCursors() [][]byte {
	if m != nil {
		return m.ChangeCursors
	}
	return nil
}

type QueryWarehouseRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Partitions           int32    `protobuf:"varint,3,opt,name=partitions,proto3" json:"partitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryWarehouseRequest) Reset()         { *m = QueryWarehouseRequest{} }
func (m *QueryWarehouseRequest) String() string { return proto.CompactTextString(m) }
func (*QueryWarehouseRequest) ProtoMessage()    {}
func (*QueryWarehouseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a2419213bb16, []int{11}
}

func (m *QueryWarehouseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryWarehouseRequest.Unmarshal(m, b)
}
func (m *QueryWarehouseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryWarehouseRequest.Marshal(b, m, deterministic)
}
func (m *QueryWarehouseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWarehouseRequest.Merge(m, src)
}
func (m *QueryWarehouseRequest) XXX_Size() int {
	return xxx_messageInfo_QueryWarehouseRequest.Size(m)
}
func (m *QueryWarehouseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWarehouseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWarehouseRequest proto.InternalMessageInfo

func (m *QueryWarehouseRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *QueryWarehouseRequest) GetPartitions() int32 {
	if m != nil {
		return m.Partitions
	}
	return 0
}

type QueryWarehouseResponse struct {
	Job                  *WarehouseJob `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *QueryWarehouseResponse) Reset()         { *m = QueryWarehouseResponse{} }
func (m *QueryWarehouseResponse) String() string { return proto.CompactTextString(m) }
func (*QueryWarehouseResponse) ProtoMessage()    {}
func (*QueryWarehouseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a2419213bb16, []int{12}
}

func (m *QueryWarehouseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryWarehouseResponse.Unmarshal(m, b)
}
func (m *QueryWarehouseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryWarehouseResponse.Marshal(b, m, deterministic)
}
func (m *QueryWarehouseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWarehouseResponse.Merge(m, src)
}
func (m *QueryWarehouseResponse) XXX_Size() int {
	return xxx_messageInfo_QueryWarehouseResponse.Size(m)
}
func (m *QueryWarehouseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWarehouseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWarehouseResponse proto.InternalMessageInfo

func (m *QueryWarehouseResponse) GetJob() *WarehouseJob {
	if m != nil {
		return m.Job
	}
	return nil
}

type PollWarehouseJobRequest struct {
	JobId                []byte   `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PollWarehouseJobRequest) Reset()         { *m = PollWarehouseJobRequest{} }
func (m *PollWarehouseJobRequest) String() string { return proto.CompactTextString(m) }
func (*PollWarehouseJobRequest) ProtoMessage()    {}
func (*PollWarehouseJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a2419213bb16, []int{13}
}

func (m *PollWarehouseJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PollWarehouseJobRequest.Unmarshal(m, b)
}
func (m *PollWarehouseJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PollWarehouseJobRequest.Marshal(b, m, deterministic)
}
func (m *PollWarehouseJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollWarehouseJobRequest.Merge(m, src)
}
func (m *PollWarehouseJobRequest) XXX_Size() int {
	return xxx_messageInfo_PollWarehouseJobRequest.Size(m)
}
func (m *PollWarehouseJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PollWarehouseJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PollWarehouseJobRequest proto.InternalMessageInfo

func (m *PollWarehouseJobRequest) GetJobId() []byte {
	if m != nil {
		return m.JobId
	}
	return nil
}

type PollWarehouseJobResponse struct {
	Job                  *WarehouseJob `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PollWarehouseJobResponse) Reset()         { *m = PollWarehouseJobResponse{} }
func (m *PollWarehouseJobResponse) String() string { return proto.CompactTextString(m) }
func (*PollWarehouseJobResponse) ProtoMessage()    {}
func (*PollWarehouseJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a2419213bb16, []int{14}
}

func (m *PollWarehouseJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PollWarehouseJobResponse.Unmarshal(m, b)
}
func (m *PollWarehouseJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PollWarehouseJobResponse.Marshal(b, m, deterministic)
}
func (m *PollWarehouseJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollWarehouseJobResponse.Merge(m, src)
}
func (m *PollWarehouseJobResponse) XXX_Size() int {
	return xxx_messageInfo_PollWarehouseJobResponse.Size(m)
}
func (m *PollWarehouseJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PollWarehouseJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PollWarehouseJobResponse proto.InternalMessageInfo

func (m *PollWarehouseJobResponse) GetJob() *WarehouseJob {
	if m != nil {
		return m.Job
	}
	return nil
}

type ReadRequest struct {
	Cursor               []byte   `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a2419213bb16, []int{15}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetCursor() []byte {
	if m != nil {
		return m.Cursor
	}
	return nil
}

func (m *ReadRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ReadResponse struct {
	Records              []*Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	NextCursor           []byte    `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a2419213bb16, []int{16}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

func (m *ReadResponse) GetNextCursor() []byte {
	if m != nil {
		return m.NextCursor
	}
	return nil
}

type SubscribeRequest struct {
	Cursor               []byte   `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a2419213bb16, []int{17}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetCursor() []byte {
	if m != nil {
		return m.Cursor
	}
	return nil
}

type SubscribeResponse struct {
	WriteId              []byte   `protobuf:"bytes,1,opt,name=write_id,json=writeId,proto3" json:"write_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeResponse) Reset()         { *m = SubscribeResponse{} }
func (m *SubscribeResponse) String() string { return proto.CompactTextString(m) }
func (*SubscribeResponse) ProtoMessage()    {}
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a2419213bb16, []int{18}
}

func (m *SubscribeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeResponse.Unmarshal(m, b)
}
func (m *SubscribeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeResponse.Marshal(b, m, deterministic)
}
func (m *SubscribeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeResponse.Merge(m, src)
}
func (m *SubscribeResponse) XXX_Size() int {
	return xxx_messageInfo_SubscribeResponse.Size(m)
}
func (m *SubscribeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeResponse proto.InternalMessageInfo

func (m *SubscribeResponse) GetWriteId() []byte {
	if m != nil {
		return m.WriteId
	}
	return nil
}

func init() {
	proto.RegisterType((*Record)(nil), "gateway.v1.Record")
	proto.RegisterType((*InstanceRecords)(nil), "gateway.v1.InstanceRecords")
	proto.RegisterType((*WarehouseJob)(nil), "gateway.v1.WarehouseJob")
	proto.RegisterType((*PingRequest)(nil), "gateway.v1.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "gateway.v1.PingResponse")
	proto.RegisterType((*WriteRequest)(nil), "gateway.v1.WriteRequest")
	proto.RegisterType((*WriteResponse)(nil), "gateway.v1.WriteResponse")
	proto.RegisterType((*QueryLogRequest)(nil), "gateway.v1.QueryLogRequest")
	proto.RegisterType((*QueryLogResponse)(nil), "gateway.v1.QueryLogResponse")
	proto.RegisterType((*QueryIndexRequest)(nil), "gateway.v1.QueryIndexRequest")
	proto.RegisterType((*QueryIndexResponse)(nil), "gateway.v1.QueryIndexResponse")
	proto.RegisterType((*QueryWarehouseRequest)(nil), "gateway.v1.QueryWarehouseRequest")
	proto.RegisterType((*QueryWarehouseResponse)(nil), "gateway.v1.QueryWarehouseResponse")
	proto.RegisterType((*PollWarehouseJobRequest)(nil), "gateway.v1.PollWarehouseJobRequest")
	proto.RegisterType((*PollWarehouseJobResponse)(nil), "gateway.v1.PollWarehouseJobResponse")
	proto.RegisterType((*ReadRequest)(nil), "gateway.v1.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "gateway.v1.ReadResponse")
	proto.RegisterType((*SubscribeRequest)(nil), "gateway.v1.SubscribeRequest")
	proto.RegisterType((*SubscribeResponse)(nil), "gateway.v1.SubscribeResponse")
}

func init() { proto.RegisterFile("gateway/grpc/proto/gateway.proto", fileDescriptor_1fb7a2419213bb16) }

var fileDescriptor_1fb7a2419213bb16 = []byte{
	// 798 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xeb, 0x4e, 0xe3, 0x46,
	0x14, 0x26, 0xe4, 0x42, 0x72, 0x92, 0x40, 0x98, 0x16, 0x08, 0xe1, 0xd2, 0x74, 0x0a, 0x12, 0x42,
	0x6d, 0x42, 0xd3, 0x9f, 0x48, 0xfd, 0x51, 0x10, 0x28, 0x15, 0x48, 0x60, 0x24, 0xd0, 0xae, 0xb4,
	0x0a, 0x63, 0x7b, 0x48, 0x86, 0x75, 0x3c, 0xc1, 0x9e, 0x70, 0x79, 0x87, 0x7d, 0xcd, 0x7d, 0x8f,
	0x95, 0x67, 0xc6, 0x8e, 0xed, 0x00, 0x91, 0x56, 0xbb, 0xbf, 0xe2, 0xf3, 0x9d, 0x33, 0xdf, 0xb9,
	0x1f, 0x05, 0x9a, 0x7d, 0x22, 0xe8, 0x13, 0x79, 0x69, 0xf7, 0xbd, 0x91, 0xd5, 0x1e, 0x79, 0x5c,
	0xf0, 0xb6, 0x86, 0x5a, 0x52, 0x42, 0x10, 0x8a, 0x8f, 0x7f, 0xe3, 0x23, 0x28, 0x18, 0xd4, 0xe2,
	0x9e, 0x8d, 0x36, 0xa0, 0x44, 0x1e, 0x3d, 0xde, 0xb3, 0x89, 0x20, 0xf5, 0x4c, 0x33, 0xb3, 0x57,
	0x31, 0x8a, 0x01, 0x70, 0x4c, 0x04, 0x41, 0x9b, 0x50, 0x12, 0x6c, 0x48, 0x7d, 0x41, 0x86, 0xa3,
	0xfa, 0x7c, 0x33, 0xb3, 0x97, 0x35, 0x26, 0x00, 0xbe, 0x85, 0xa5, 0xae, 0xeb, 0x0b, 0xe2, 0x5a,
	0x54, 0x91, 0xf9, 0xe8, 0x37, 0x28, 0x33, 0x0d, 0xf5, 0x98, 0xad, 0xf9, 0x20, 0x84, 0xba, 0x36,
	0xfa, 0x13, 0x16, 0x3c, 0x65, 0x5b, 0x9f, 0x6f, 0x66, 0xf7, 0xca, 0x1d, 0xd4, 0x9a, 0x84, 0xd5,
	0x52, 0x34, 0x46, 0x68, 0x82, 0x77, 0xa1, 0x72, 0x43, 0x3c, 0x3a, 0xe0, 0x63, 0x9f, 0xfe, 0xcf,
	0x4d, 0xb4, 0x02, 0x85, 0x7b, 0x6e, 0x4e, 0x98, 0xf3, 0xf7, 0xdc, 0xec, 0xda, 0xf8, 0x12, 0xca,
	0x17, 0xcc, 0xed, 0x1b, 0xf4, 0x61, 0x4c, 0x7d, 0x11, 0xa4, 0x64, 0x39, 0x8c, 0xba, 0x22, 0x34,
	0x2c, 0x19, 0x45, 0x05, 0x74, 0x6d, 0xb4, 0x0b, 0x8b, 0x5a, 0xf9, 0x48, 0x3d, 0x9f, 0x71, 0x57,
	0xe6, 0x55, 0x32, 0xaa, 0x0a, 0xbd, 0x56, 0x20, 0xfe, 0x92, 0x81, 0x8a, 0xe2, 0xf4, 0x47, 0xdc,
	0xf5, 0x29, 0xda, 0x81, 0x2a, 0x19, 0x8b, 0x01, 0x75, 0x05, 0xb3, 0x88, 0xa0, 0x8a, 0xb8, 0x68,
	0x24, 0xc1, 0x80, 0x5d, 0xd3, 0xf6, 0x7c, 0x41, 0xc4, 0xd8, 0x0f, 0xd9, 0x35, 0x7a, 0x25, 0x41,
	0xd4, 0x86, 0x5f, 0x82, 0x14, 0x87, 0x43, 0xea, 0xda, 0xd4, 0x8e, 0x22, 0xc9, 0x4a, 0x5b, 0x14,
	0x53, 0x85, 0xe1, 0x5c, 0x43, 0xe5, 0xc6, 0x63, 0x82, 0x86, 0x29, 0x9e, 0x40, 0x2d, 0xaa, 0x73,
	0x58, 0xcf, 0x8c, 0xac, 0xe7, 0x46, 0xbc, 0x9e, 0xa9, 0xf6, 0x18, 0x4b, 0x2c, 0x09, 0xe0, 0x7d,
	0xa8, 0x6a, 0x5e, 0x9d, 0xe6, 0x3a, 0x14, 0x9f, 0x02, 0x60, 0x52, 0xe3, 0x05, 0x29, 0x77, 0x6d,
	0x7c, 0x07, 0x4b, 0x97, 0x63, 0xea, 0xbd, 0x9c, 0xf1, 0xa8, 0xd2, 0x33, 0xdb, 0xbd, 0x0d, 0x30,
	0x22, 0x9e, 0x60, 0x82, 0x71, 0x57, 0xd5, 0x22, 0x6f, 0xc4, 0x10, 0x84, 0x20, 0x37, 0xa2, 0xf4,
	0xb3, 0xcc, 0xbc, 0x68, 0xc8, 0x6f, 0x7c, 0x0b, 0xb5, 0x89, 0x1f, 0x1d, 0xd6, 0x2e, 0x2c, 0x7a,
	0x74, 0xe4, 0x90, 0x97, 0x9e, 0x35, 0xf6, 0x7c, 0xee, 0xa9, 0x6c, 0x2b, 0x46, 0x55, 0xa1, 0x47,
	0x0a, 0x94, 0xcd, 0x1d, 0x10, 0xb7, 0x4f, 0x23, 0xb3, 0x79, 0x65, 0xa6, 0x50, 0x6d, 0x86, 0x1d,
	0x58, 0x96, 0x1e, 0xba, 0xae, 0x4d, 0x9f, 0x7f, 0x58, 0x2e, 0xab, 0x50, 0xb8, 0x63, 0x8e, 0xa0,
	0x9e, 0xee, 0xa3, 0x96, 0xb0, 0x09, 0x28, 0xee, 0xed, 0xa7, 0x64, 0x74, 0x0e, 0x2b, 0xd2, 0x47,
	0xb4, 0x2d, 0x61, 0x56, 0xbf, 0x42, 0xfe, 0x21, 0x50, 0xe8, 0x3d, 0x50, 0x42, 0x2a, 0x95, 0x6c,
	0x3a, 0x15, 0x7c, 0x0c, 0xab, 0x69, 0x3a, 0x1d, 0xf6, 0x3e, 0x64, 0xef, 0xb9, 0x29, 0xd9, 0xca,
	0x9d, 0x7a, 0x7c, 0xd6, 0xe2, 0x8b, 0x6a, 0x04, 0x46, 0xf8, 0x00, 0xd6, 0x2e, 0xb8, 0xe3, 0x24,
	0x14, 0x3a, 0xac, 0x37, 0x16, 0xf9, 0x04, 0xea, 0xd3, 0x2f, 0xbe, 0xc3, 0xf3, 0x21, 0x94, 0x0d,
	0x4a, 0xec, 0xd0, 0xdb, 0x2a, 0x14, 0x54, 0xf5, 0x64, 0xd7, 0x2a, 0x86, 0x96, 0x82, 0xe2, 0x38,
	0x6c, 0xc8, 0x84, 0xae, 0x80, 0x12, 0xf0, 0x27, 0xa8, 0xa8, 0xc7, 0xda, 0x71, 0xec, 0x64, 0x65,
	0x66, 0x9e, 0xac, 0x60, 0x8c, 0x5c, 0xfa, 0x2c, 0x7a, 0x09, 0x87, 0x10, 0x40, 0xaa, 0x57, 0x78,
	0x1f, 0x6a, 0x57, 0x63, 0xd3, 0xb7, 0x3c, 0x66, 0xd2, 0x19, 0x01, 0xe2, 0x16, 0x2c, 0xc7, 0x6c,
	0x67, 0xae, 0x68, 0xe7, 0x6b, 0x0e, 0x16, 0x4e, 0x55, 0x6c, 0xe8, 0x10, 0x72, 0xc1, 0x01, 0x43,
	0x6b, 0xf1, 0x68, 0x63, 0x67, 0xb2, 0x51, 0x9f, 0x56, 0x28, 0x0f, 0x78, 0x0e, 0xfd, 0x0b, 0x79,
	0x79, 0x17, 0x50, 0xb2, 0xd0, 0xb1, 0x13, 0xd4, 0x58, 0x7f, 0x45, 0x13, 0xbd, 0x3f, 0x85, 0x62,
	0xb8, 0xc3, 0x28, 0x71, 0x91, 0x52, 0x17, 0xa4, 0xb1, 0xf9, 0xba, 0x32, 0x22, 0x3a, 0x07, 0x98,
	0x2c, 0x0f, 0xda, 0x9a, 0xb2, 0x8e, 0xaf, 0x70, 0x63, 0xfb, 0x2d, 0x75, 0x44, 0xf7, 0x01, 0x16,
	0x93, 0x83, 0x8d, 0x7e, 0x9f, 0x7a, 0x93, 0xde, 0xa1, 0x06, 0x7e, 0xcf, 0x24, 0xa2, 0xee, 0x41,
	0x2d, 0x3d, 0xbb, 0xe8, 0x8f, 0x44, 0x89, 0x5f, 0xdf, 0x85, 0xc6, 0xce, 0xfb, 0x46, 0x91, 0x83,
	0x43, 0xc8, 0x05, 0x73, 0x99, 0x6c, 0x68, 0x6c, 0xcc, 0x93, 0x0d, 0x8d, 0x8f, 0x30, 0x9e, 0x43,
	0x67, 0x50, 0x8a, 0x26, 0x09, 0x25, 0x8a, 0x9e, 0x1e, 0xc6, 0xc6, 0xd6, 0x1b, 0xda, 0x90, 0xeb,
	0x20, 0xf3, 0x5f, 0xe7, 0xe3, 0x41, 0x9f, 0x09, 0x87, 0x98, 0x2d, 0x8b, 0x0f, 0xdb, 0x26, 0x75,
	0x29, 0x11, 0x83, 0xbf, 0x06, 0x0f, 0xe1, 0x67, 0x7b, 0xfa, 0xcf, 0x88, 0x59, 0x90, 0x3f, 0xff,
	0x7c, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x60, 0xf0, 0x3c, 0xa9, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GatewayClient is the client API for Gateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GatewayClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	QueryLog(ctx context.Context, in *QueryLogRequest, opts ...grpc.CallOption) (*QueryLogResponse, error)
	QueryIndex(ctx context.Context, in *QueryIndexRequest, opts ...grpc.CallOption) (*QueryIndexResponse, error)
	QueryWarehouse(ctx context.Context, in *QueryWarehouseRequest, opts ...grpc.CallOption) (*QueryWarehouseResponse, error)
	PollWarehouseJob(ctx context.Context, in *PollWarehouseJobRequest, opts ...grpc.CallOption) (*PollWarehouseJobResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Gateway_SubscribeClient, error)
}

type gatewayClient struct {
	cc *grpc.ClientConn
}

func NewGatewayClient(cc *grpc.ClientConn) GatewayClient {
	return &gatewayClient{cc}
}

func (c *gatewayClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/gateway.v1.Gateway/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, "/gateway.v1.Gateway/Write", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) QueryLog(ctx context.Context, in *QueryLogRequest, opts ...grpc.CallOption) (*QueryLogResponse, error) {
	out := new(QueryLogResponse)
	err := c.cc.Invoke(ctx, "/gateway.v1.Gateway/QueryLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) QueryIndex(ctx context.Context, in *QueryIndexRequest, opts ...grpc.CallOption) (*QueryIndexResponse, error) {
	out := new(QueryIndexResponse)
	err := c.cc.Invoke(ctx, "/gateway.v1.Gateway/QueryIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) QueryWarehouse(ctx context.Context, in *QueryWarehouseRequest, opts ...grpc.CallOption) (*QueryWarehouseResponse, error) {
	out := new(QueryWarehouseResponse)
	err := c.cc.Invoke(ctx, "/gateway.v1.Gateway/QueryWarehouse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) PollWarehouseJob(ctx context.Context, in *PollWarehouseJobRequest, opts ...grpc.CallOption) (*PollWarehouseJobResponse, error) {
	out := new(PollWarehouseJobResponse)
	err := c.cc.Invoke(ctx, "/gateway.v1.Gateway/PollWarehouseJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, "/gateway.v1.Gateway/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Gateway_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Gateway_serviceDesc.Streams[0], "/gateway.v1.Gateway/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &gatewaySubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Gateway_SubscribeClient interface {
	Recv() (*SubscribeResponse, error)
	grpc.ClientStream
}

type gatewaySubscribeClient struct {
	grpc.ClientStream
}

func (x *gatewaySubscribeClient) Recv() (*SubscribeResponse, error) {
	m := new(SubscribeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GatewayServer is the server API for Gateway service.
type GatewayServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	QueryLog(context.Context, *QueryLogRequest) (*QueryLogResponse, error)
	QueryIndex(context.Context, *QueryIndexRequest) (*QueryIndexResponse, error)
	QueryWarehouse(context.Context, *QueryWarehouseRequest) (*QueryWarehouseResponse, error)
	PollWarehouseJob(context.Context, *PollWarehouseJobRequest) (*PollWarehouseJobResponse, error)
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	Subscribe(*SubscribeRequest, Gateway_SubscribeServer) error
}

// UnimplementedGatewayServer can be embedded to have forward compatible implementations.
type UnimplementedGatewayServer struct {
}

func (*UnimplementedGatewayServer) Ping(ctx context.Context, req *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedGatewayServer) Write(ctx context.Context, req *WriteRequest) (*WriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (*UnimplementedGatewayServer) QueryLog(ctx context.Context, req *QueryLogRequest) (*QueryLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryLog not implemented")
}
func (*UnimplementedGatewayServer) QueryIndex(ctx context.Context, req *QueryIndexRequest) (*QueryIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryIndex not implemented")
}
func (*UnimplementedGatewayServer) QueryWarehouse(ctx context.Context, req *QueryWarehouseRequest) (*QueryWarehouseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryWarehouse not implemented")
}
func (*UnimplementedGatewayServer) PollWarehouseJob(ctx context.Context, req *PollWarehouseJobRequest) (*PollWarehouseJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PollWarehouseJob not implemented")
}
func (*UnimplementedGatewayServer) Read(ctx context.Context, req *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (*UnimplementedGatewayServer) Subscribe(req *SubscribeRequest, srv Gateway_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}

func RegisterGatewayServer(s *grpc.Server, srv GatewayServer) {
	s.RegisterService(&_Gateway_serviceDesc, srv)
}

func _Gateway_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.v1.Gateway/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.v1.Gateway/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_QueryLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).QueryLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.v1.Gateway/QueryLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).QueryLog(ctx, req.(*QueryLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_QueryIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).QueryIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.v1.Gateway/QueryIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).QueryIndex(ctx, req.(*QueryIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_QueryWarehouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryWarehouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).QueryWarehouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.v1.Gateway/QueryWarehouse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).QueryWarehouse(ctx, req.(*QueryWarehouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_PollWarehouseJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollWarehouseJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).PollWarehouseJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.v1.Gateway/PollWarehouseJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).PollWarehouseJob(ctx, req.(*PollWarehouseJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.v1.Gateway/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatewayServer).Subscribe(m, &gatewaySubscribeServer{stream})
}

type Gateway_SubscribeServer interface {
	Send(*SubscribeResponse) error
	grpc.ServerStream
}

type gatewaySubscribeServer struct {
	grpc.ServerStream
}

func (x *gatewaySubscribeServer) Send(m *SubscribeResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Gateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.v1.Gateway",
	HandlerType: (*GatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Gateway_Ping_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _Gateway_Write_Handler,
		},
		{
			MethodName: "QueryLog",
			Handler:    _Gateway_QueryLog_Handler,
		},
		{
			MethodName: "QueryIndex",
			Handler:    _Gateway_QueryIndex_Handler,
		},
		{
			MethodName: "QueryWarehouse",
			Handler:    _Gateway_QueryWarehouse_Handler,
		},
		{
			MethodName: "PollWarehouseJob",
			Handler:    _Gateway_PollWarehouseJob_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Gateway_Read_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Gateway_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gateway/grpc/proto/gateway.proto",
}
