# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from beneath.proto import gateway_pb2 as beneath_dot_proto_dot_gateway__pb2


class GatewayStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Query = channel.unary_unary(
        '/gateway.Gateway/Query',
        request_serializer=beneath_dot_proto_dot_gateway__pb2.QueryRequest.SerializeToString,
        response_deserializer=beneath_dot_proto_dot_gateway__pb2.QueryResponse.FromString,
        )
    self.Read = channel.unary_unary(
        '/gateway.Gateway/Read',
        request_serializer=beneath_dot_proto_dot_gateway__pb2.ReadRequest.SerializeToString,
        response_deserializer=beneath_dot_proto_dot_gateway__pb2.ReadResponse.FromString,
        )
    self.Subscribe = channel.unary_stream(
        '/gateway.Gateway/Subscribe',
        request_serializer=beneath_dot_proto_dot_gateway__pb2.SubscribeRequest.SerializeToString,
        response_deserializer=beneath_dot_proto_dot_gateway__pb2.SubscribeResponse.FromString,
        )
    self.Peek = channel.unary_unary(
        '/gateway.Gateway/Peek',
        request_serializer=beneath_dot_proto_dot_gateway__pb2.PeekRequest.SerializeToString,
        response_deserializer=beneath_dot_proto_dot_gateway__pb2.PeekResponse.FromString,
        )
    self.Repartition = channel.unary_unary(
        '/gateway.Gateway/Repartition',
        request_serializer=beneath_dot_proto_dot_gateway__pb2.RepartitionRequest.SerializeToString,
        response_deserializer=beneath_dot_proto_dot_gateway__pb2.RepartitionResponse.FromString,
        )
    self.Write = channel.unary_unary(
        '/gateway.Gateway/Write',
        request_serializer=beneath_dot_proto_dot_gateway__pb2.WriteRequest.SerializeToString,
        response_deserializer=beneath_dot_proto_dot_gateway__pb2.WriteResponse.FromString,
        )
    self.Ping = channel.unary_unary(
        '/gateway.Gateway/Ping',
        request_serializer=beneath_dot_proto_dot_gateway__pb2.PingRequest.SerializeToString,
        response_deserializer=beneath_dot_proto_dot_gateway__pb2.PingResponse.FromString,
        )
    self.GetStream = channel.unary_unary(
        '/gateway.Gateway/GetStream',
        request_serializer=beneath_dot_proto_dot_gateway__pb2.GetStreamRequest.SerializeToString,
        response_deserializer=beneath_dot_proto_dot_gateway__pb2.GetStreamResponse.FromString,
        )


class GatewayServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Query(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Read(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Subscribe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Peek(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Repartition(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Write(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Ping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GatewayServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Query': grpc.unary_unary_rpc_method_handler(
          servicer.Query,
          request_deserializer=beneath_dot_proto_dot_gateway__pb2.QueryRequest.FromString,
          response_serializer=beneath_dot_proto_dot_gateway__pb2.QueryResponse.SerializeToString,
      ),
      'Read': grpc.unary_unary_rpc_method_handler(
          servicer.Read,
          request_deserializer=beneath_dot_proto_dot_gateway__pb2.ReadRequest.FromString,
          response_serializer=beneath_dot_proto_dot_gateway__pb2.ReadResponse.SerializeToString,
      ),
      'Subscribe': grpc.unary_stream_rpc_method_handler(
          servicer.Subscribe,
          request_deserializer=beneath_dot_proto_dot_gateway__pb2.SubscribeRequest.FromString,
          response_serializer=beneath_dot_proto_dot_gateway__pb2.SubscribeResponse.SerializeToString,
      ),
      'Peek': grpc.unary_unary_rpc_method_handler(
          servicer.Peek,
          request_deserializer=beneath_dot_proto_dot_gateway__pb2.PeekRequest.FromString,
          response_serializer=beneath_dot_proto_dot_gateway__pb2.PeekResponse.SerializeToString,
      ),
      'Repartition': grpc.unary_unary_rpc_method_handler(
          servicer.Repartition,
          request_deserializer=beneath_dot_proto_dot_gateway__pb2.RepartitionRequest.FromString,
          response_serializer=beneath_dot_proto_dot_gateway__pb2.RepartitionResponse.SerializeToString,
      ),
      'Write': grpc.unary_unary_rpc_method_handler(
          servicer.Write,
          request_deserializer=beneath_dot_proto_dot_gateway__pb2.WriteRequest.FromString,
          response_serializer=beneath_dot_proto_dot_gateway__pb2.WriteResponse.SerializeToString,
      ),
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=beneath_dot_proto_dot_gateway__pb2.PingRequest.FromString,
          response_serializer=beneath_dot_proto_dot_gateway__pb2.PingResponse.SerializeToString,
      ),
      'GetStream': grpc.unary_unary_rpc_method_handler(
          servicer.GetStream,
          request_deserializer=beneath_dot_proto_dot_gateway__pb2.GetStreamRequest.FromString,
          response_serializer=beneath_dot_proto_dot_gateway__pb2.GetStreamResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gateway.Gateway', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
