# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from beneath.proto import gateway_pb2 as beneath_dot_proto_dot_gateway__pb2


class GatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/gateway.v1.Gateway/Ping',
                request_serializer=beneath_dot_proto_dot_gateway__pb2.PingRequest.SerializeToString,
                response_deserializer=beneath_dot_proto_dot_gateway__pb2.PingResponse.FromString,
                )
        self.Write = channel.unary_unary(
                '/gateway.v1.Gateway/Write',
                request_serializer=beneath_dot_proto_dot_gateway__pb2.WriteRequest.SerializeToString,
                response_deserializer=beneath_dot_proto_dot_gateway__pb2.WriteResponse.FromString,
                )
        self.QueryLog = channel.unary_unary(
                '/gateway.v1.Gateway/QueryLog',
                request_serializer=beneath_dot_proto_dot_gateway__pb2.QueryLogRequest.SerializeToString,
                response_deserializer=beneath_dot_proto_dot_gateway__pb2.QueryLogResponse.FromString,
                )
        self.QueryIndex = channel.unary_unary(
                '/gateway.v1.Gateway/QueryIndex',
                request_serializer=beneath_dot_proto_dot_gateway__pb2.QueryIndexRequest.SerializeToString,
                response_deserializer=beneath_dot_proto_dot_gateway__pb2.QueryIndexResponse.FromString,
                )
        self.QueryWarehouse = channel.unary_unary(
                '/gateway.v1.Gateway/QueryWarehouse',
                request_serializer=beneath_dot_proto_dot_gateway__pb2.QueryWarehouseRequest.SerializeToString,
                response_deserializer=beneath_dot_proto_dot_gateway__pb2.QueryWarehouseResponse.FromString,
                )
        self.PollWarehouseJob = channel.unary_unary(
                '/gateway.v1.Gateway/PollWarehouseJob',
                request_serializer=beneath_dot_proto_dot_gateway__pb2.PollWarehouseJobRequest.SerializeToString,
                response_deserializer=beneath_dot_proto_dot_gateway__pb2.PollWarehouseJobResponse.FromString,
                )
        self.Read = channel.unary_unary(
                '/gateway.v1.Gateway/Read',
                request_serializer=beneath_dot_proto_dot_gateway__pb2.ReadRequest.SerializeToString,
                response_deserializer=beneath_dot_proto_dot_gateway__pb2.ReadResponse.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/gateway.v1.Gateway/Subscribe',
                request_serializer=beneath_dot_proto_dot_gateway__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=beneath_dot_proto_dot_gateway__pb2.SubscribeResponse.FromString,
                )


class GatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryWarehouse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollWarehouseJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=beneath_dot_proto_dot_gateway__pb2.PingRequest.FromString,
                    response_serializer=beneath_dot_proto_dot_gateway__pb2.PingResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=beneath_dot_proto_dot_gateway__pb2.WriteRequest.FromString,
                    response_serializer=beneath_dot_proto_dot_gateway__pb2.WriteResponse.SerializeToString,
            ),
            'QueryLog': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryLog,
                    request_deserializer=beneath_dot_proto_dot_gateway__pb2.QueryLogRequest.FromString,
                    response_serializer=beneath_dot_proto_dot_gateway__pb2.QueryLogResponse.SerializeToString,
            ),
            'QueryIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryIndex,
                    request_deserializer=beneath_dot_proto_dot_gateway__pb2.QueryIndexRequest.FromString,
                    response_serializer=beneath_dot_proto_dot_gateway__pb2.QueryIndexResponse.SerializeToString,
            ),
            'QueryWarehouse': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryWarehouse,
                    request_deserializer=beneath_dot_proto_dot_gateway__pb2.QueryWarehouseRequest.FromString,
                    response_serializer=beneath_dot_proto_dot_gateway__pb2.QueryWarehouseResponse.SerializeToString,
            ),
            'PollWarehouseJob': grpc.unary_unary_rpc_method_handler(
                    servicer.PollWarehouseJob,
                    request_deserializer=beneath_dot_proto_dot_gateway__pb2.PollWarehouseJobRequest.FromString,
                    response_serializer=beneath_dot_proto_dot_gateway__pb2.PollWarehouseJobResponse.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=beneath_dot_proto_dot_gateway__pb2.ReadRequest.FromString,
                    response_serializer=beneath_dot_proto_dot_gateway__pb2.ReadResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=beneath_dot_proto_dot_gateway__pb2.SubscribeRequest.FromString,
                    response_serializer=beneath_dot_proto_dot_gateway__pb2.SubscribeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gateway.v1.Gateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Gateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gateway.v1.Gateway/Ping',
            beneath_dot_proto_dot_gateway__pb2.PingRequest.SerializeToString,
            beneath_dot_proto_dot_gateway__pb2.PingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gateway.v1.Gateway/Write',
            beneath_dot_proto_dot_gateway__pb2.WriteRequest.SerializeToString,
            beneath_dot_proto_dot_gateway__pb2.WriteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gateway.v1.Gateway/QueryLog',
            beneath_dot_proto_dot_gateway__pb2.QueryLogRequest.SerializeToString,
            beneath_dot_proto_dot_gateway__pb2.QueryLogResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gateway.v1.Gateway/QueryIndex',
            beneath_dot_proto_dot_gateway__pb2.QueryIndexRequest.SerializeToString,
            beneath_dot_proto_dot_gateway__pb2.QueryIndexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryWarehouse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gateway.v1.Gateway/QueryWarehouse',
            beneath_dot_proto_dot_gateway__pb2.QueryWarehouseRequest.SerializeToString,
            beneath_dot_proto_dot_gateway__pb2.QueryWarehouseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PollWarehouseJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gateway.v1.Gateway/PollWarehouseJob',
            beneath_dot_proto_dot_gateway__pb2.PollWarehouseJobRequest.SerializeToString,
            beneath_dot_proto_dot_gateway__pb2.PollWarehouseJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gateway.v1.Gateway/Read',
            beneath_dot_proto_dot_gateway__pb2.ReadRequest.SerializeToString,
            beneath_dot_proto_dot_gateway__pb2.ReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/gateway.v1.Gateway/Subscribe',
            beneath_dot_proto_dot_gateway__pb2.SubscribeRequest.SerializeToString,
            beneath_dot_proto_dot_gateway__pb2.SubscribeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
