// Code generated by protoc-gen-go. DO NOT EDIT.
// source: platform.proto

package beneath_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EncodedRecord struct {
	SequenceNumber       []byte   `protobuf:"bytes,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncodedRecord) Reset()         { *m = EncodedRecord{} }
func (m *EncodedRecord) String() string { return proto.CompactTextString(m) }
func (*EncodedRecord) ProtoMessage()    {}
func (*EncodedRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_918f3d50bfb447e4, []int{0}
}

func (m *EncodedRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncodedRecord.Unmarshal(m, b)
}
func (m *EncodedRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncodedRecord.Marshal(b, m, deterministic)
}
func (m *EncodedRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncodedRecord.Merge(m, src)
}
func (m *EncodedRecord) XXX_Size() int {
	return xxx_messageInfo_EncodedRecord.Size(m)
}
func (m *EncodedRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_EncodedRecord.DiscardUnknown(m)
}

var xxx_messageInfo_EncodedRecord proto.InternalMessageInfo

func (m *EncodedRecord) GetSequenceNumber() []byte {
	if m != nil {
		return m.SequenceNumber
	}
	return nil
}

func (m *EncodedRecord) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *EncodedRecord) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type WriteEncodedRecordsRequest struct {
	InstanceId           []byte           `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Records              []*EncodedRecord `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *WriteEncodedRecordsRequest) Reset()         { *m = WriteEncodedRecordsRequest{} }
func (m *WriteEncodedRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*WriteEncodedRecordsRequest) ProtoMessage()    {}
func (*WriteEncodedRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_918f3d50bfb447e4, []int{1}
}

func (m *WriteEncodedRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteEncodedRecordsRequest.Unmarshal(m, b)
}
func (m *WriteEncodedRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteEncodedRecordsRequest.Marshal(b, m, deterministic)
}
func (m *WriteEncodedRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteEncodedRecordsRequest.Merge(m, src)
}
func (m *WriteEncodedRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_WriteEncodedRecordsRequest.Size(m)
}
func (m *WriteEncodedRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteEncodedRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteEncodedRecordsRequest proto.InternalMessageInfo

func (m *WriteEncodedRecordsRequest) GetInstanceId() []byte {
	if m != nil {
		return m.InstanceId
	}
	return nil
}

func (m *WriteEncodedRecordsRequest) GetRecords() []*EncodedRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

func init() {
	proto.RegisterType((*EncodedRecord)(nil), "beneath_proto.EncodedRecord")
	proto.RegisterType((*WriteEncodedRecordsRequest)(nil), "beneath_proto.WriteEncodedRecordsRequest")
}

func init() { proto.RegisterFile("platform.proto", fileDescriptor_918f3d50bfb447e4) }

var fileDescriptor_918f3d50bfb447e4 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x3f, 0x4b, 0xc5, 0x30,
	0x14, 0xc5, 0xe9, 0xab, 0x28, 0xdc, 0xf7, 0x47, 0x09, 0x08, 0x41, 0x04, 0x4b, 0x97, 0x76, 0xea,
	0xa0, 0xe0, 0x07, 0x28, 0x38, 0xb8, 0x48, 0xc9, 0xe2, 0x66, 0x49, 0x9b, 0x2b, 0x96, 0xda, 0xa4,
	0x26, 0xb7, 0x88, 0xdf, 0x5e, 0x92, 0xbe, 0x0c, 0xdd, 0xce, 0xf9, 0xe5, 0xe4, 0x9c, 0x04, 0x4e,
	0xf3, 0xb7, 0xa4, 0x4f, 0x63, 0xa7, 0x6a, 0xb6, 0x86, 0x0c, 0x3b, 0x76, 0xa8, 0x51, 0xd2, 0x57,
	0x1b, 0x6c, 0xfe, 0x01, 0xc7, 0x17, 0xdd, 0x1b, 0x85, 0x4a, 0x60, 0x6f, 0xac, 0x62, 0x05, 0x5c,
	0x3b, 0xfc, 0x59, 0x50, 0xf7, 0xd8, 0xea, 0x65, 0xea, 0xd0, 0xf2, 0x24, 0x4b, 0xca, 0x83, 0x38,
	0x45, 0xfc, 0x16, 0x28, 0xbb, 0x81, 0x74, 0xc4, 0x3f, 0xbe, 0x0b, 0x87, 0x5e, 0x32, 0x06, 0x17,
	0x4a, 0x92, 0xe4, 0x69, 0x40, 0x41, 0xe7, 0x0b, 0xdc, 0xbd, 0xdb, 0x81, 0x70, 0x33, 0xe2, 0x84,
	0xaf, 0x72, 0xc4, 0x1e, 0x60, 0x3f, 0x68, 0x47, 0xd2, 0x8f, 0x0d, 0xea, 0x3c, 0x04, 0x11, 0xbd,
	0x2a, 0xf6, 0x0c, 0x57, 0x76, 0xbd, 0xc2, 0x77, 0x59, 0x5a, 0xee, 0x1f, 0xef, 0xab, 0xcd, 0xfb,
	0xab, 0x4d, 0xaf, 0x88, 0xe1, 0xba, 0x80, 0x5b, 0x8d, 0xf4, 0x6b, 0xec, 0x18, 0xf3, 0xeb, 0xf7,
	0xeb, 0x43, 0xbd, 0xda, 0xc6, 0xbb, 0x26, 0xe9, 0x2e, 0x03, 0x7e, 0xfa, 0x0f, 0x00, 0x00, 0xff,
	0xff, 0xc4, 0xc1, 0x86, 0x6f, 0x27, 0x01, 0x00, 0x00,
}
