const FREE_BILLING_PLAN_DESCRIPTION = "Free"
const PRO_BILLING_PLAN_DESCRIPTION = "Professional"

const MONTHLY_BILLING_PLAN_STRING = "Monthly"

const FREE_BILLING_PLAN_ID = "89b045b5-4234-483d-b9ef-8dd2d30c1299"
const PRO_MONTHLY_BILLING_PLAN_ID = "95c4e78d-e231-4449-a345-f0ec2ac20a7d"

const ANARCHISM_DRIVER = "anarchism"
const STRIPECARD_DRIVER = "stripecard"
const STRIPEWIRE_DRIVER = "stripewire"

module.exports = {
  FREE_BILLING_PLAN_DESCRIPTION,
  PRO_BILLING_PLAN_DESCRIPTION,
  FREE_BILLING_PLAN_ID,
  MONTHLY_BILLING_PLAN_STRING,
  PRO_MONTHLY_BILLING_PLAN_ID,
  ANARCHISM_DRIVER,
  STRIPECARD_DRIVER,
  STRIPEWIRE_DRIVER
};
