// Code generated by protoc-gen-go. DO NOT EDIT.
// source: engine.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Record struct {
	AvroData             []byte   `protobuf:"bytes,1,opt,name=avro_data,json=avroData,proto3" json:"avro_data,omitempty"`
	SequenceNumber       int64    `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_770b178c3aab763f, []int{0}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetAvroData() []byte {
	if m != nil {
		return m.AvroData
	}
	return nil
}

func (m *Record) GetSequenceNumber() int64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

type WriteRecordsRequest struct {
	InstanceId           []byte    `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Records              []*Record `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *WriteRecordsRequest) Reset()         { *m = WriteRecordsRequest{} }
func (m *WriteRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*WriteRecordsRequest) ProtoMessage()    {}
func (*WriteRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_770b178c3aab763f, []int{1}
}

func (m *WriteRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRecordsRequest.Unmarshal(m, b)
}
func (m *WriteRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRecordsRequest.Marshal(b, m, deterministic)
}
func (m *WriteRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRecordsRequest.Merge(m, src)
}
func (m *WriteRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_WriteRecordsRequest.Size(m)
}
func (m *WriteRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRecordsRequest proto.InternalMessageInfo

func (m *WriteRecordsRequest) GetInstanceId() []byte {
	if m != nil {
		return m.InstanceId
	}
	return nil
}

func (m *WriteRecordsRequest) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

func init() {
	proto.RegisterType((*Record)(nil), "proto.Record")
	proto.RegisterType((*WriteRecordsRequest)(nil), "proto.WriteRecordsRequest")
}

func init() { proto.RegisterFile("engine.proto", fileDescriptor_770b178c3aab763f) }

var fileDescriptor_770b178c3aab763f = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0xb1, 0x4a, 0xc6, 0x30,
	0x14, 0x85, 0xc9, 0x5f, 0x5a, 0xf5, 0xb6, 0x2a, 0x44, 0x84, 0x82, 0x83, 0xa1, 0x4b, 0x3b, 0x75,
	0xd0, 0x37, 0x28, 0x2e, 0x2e, 0xa5, 0x64, 0x71, 0x2c, 0x69, 0x73, 0xd1, 0x20, 0x26, 0x9a, 0xdc,
	0xea, 0xeb, 0x4b, 0x9a, 0xbf, 0xd3, 0x21, 0xdf, 0xc9, 0xf9, 0xb8, 0x50, 0xa1, 0x7d, 0x37, 0x16,
	0xfb, 0x6f, 0xef, 0xc8, 0xf1, 0x7c, 0x8f, 0x66, 0x84, 0x42, 0xe2, 0xea, 0xbc, 0xe6, 0x0f, 0x70,
	0xa5, 0x7e, 0xbd, 0x9b, 0xb5, 0x22, 0x55, 0x33, 0xc1, 0xba, 0x4a, 0x5e, 0x46, 0xf0, 0xa2, 0x48,
	0xf1, 0x16, 0x6e, 0x03, 0xfe, 0x6c, 0x68, 0x57, 0x9c, 0xed, 0xf6, 0xb5, 0xa0, 0xaf, 0x4f, 0x82,
	0x75, 0x99, 0xbc, 0x39, 0xf0, 0xb8, 0xd3, 0x66, 0x86, 0xbb, 0x37, 0x6f, 0x08, 0x93, 0x34, 0xc8,
	0xd8, 0x06, 0xe2, 0x8f, 0x50, 0x1a, 0x1b, 0x48, 0xc5, 0xbd, 0xd1, 0x67, 0x3d, 0x1c, 0xe8, 0x55,
	0xf3, 0x16, 0x2e, 0x7c, 0x9a, 0xd4, 0x27, 0x91, 0x75, 0xe5, 0xd3, 0x75, 0xba, 0xb3, 0x4f, 0x22,
	0x79, 0xb4, 0x83, 0x80, 0x7b, 0x8b, 0xf4, 0xe7, 0xfc, 0x67, 0xbf, 0xa0, 0x45, 0x45, 0x1f, 0xe9,
	0xe3, 0x90, 0x4f, 0x31, 0x26, 0xb6, 0x14, 0xfb, 0xfb, 0xf9, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x67,
	0x8f, 0xd7, 0x3b, 0xf0, 0x00, 0x00, 0x00,
}
