// Code generated by protoc-gen-go. DO NOT EDIT.
// source: engine.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Record struct {
	AvroData             []byte   `protobuf:"bytes,1,opt,name=avro_data,json=avroData,proto3" json:"avro_data,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_770b178c3aab763f, []int{0}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetAvroData() []byte {
	if m != nil {
		return m.AvroData
	}
	return nil
}

func (m *Record) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type WriteRecordsReport struct {
	InstanceId           []byte   `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	EarliestTimestamp    int64    `protobuf:"varint,2,opt,name=earliest_timestamp,json=earliestTimestamp,proto3" json:"earliest_timestamp,omitempty"`
	BytesTotal           int32    `protobuf:"varint,3,opt,name=bytes_total,json=bytesTotal,proto3" json:"bytes_total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteRecordsReport) Reset()         { *m = WriteRecordsReport{} }
func (m *WriteRecordsReport) String() string { return proto.CompactTextString(m) }
func (*WriteRecordsReport) ProtoMessage()    {}
func (*WriteRecordsReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_770b178c3aab763f, []int{1}
}

func (m *WriteRecordsReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRecordsReport.Unmarshal(m, b)
}
func (m *WriteRecordsReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRecordsReport.Marshal(b, m, deterministic)
}
func (m *WriteRecordsReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRecordsReport.Merge(m, src)
}
func (m *WriteRecordsReport) XXX_Size() int {
	return xxx_messageInfo_WriteRecordsReport.Size(m)
}
func (m *WriteRecordsReport) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRecordsReport.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRecordsReport proto.InternalMessageInfo

func (m *WriteRecordsReport) GetInstanceId() []byte {
	if m != nil {
		return m.InstanceId
	}
	return nil
}

func (m *WriteRecordsReport) GetEarliestTimestamp() int64 {
	if m != nil {
		return m.EarliestTimestamp
	}
	return 0
}

func (m *WriteRecordsReport) GetBytesTotal() int32 {
	if m != nil {
		return m.BytesTotal
	}
	return 0
}

type CursorSet struct {
	Cursors              []*Cursor `protobuf:"bytes,1,rep,name=cursors,proto3" json:"cursors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CursorSet) Reset()         { *m = CursorSet{} }
func (m *CursorSet) String() string { return proto.CompactTextString(m) }
func (*CursorSet) ProtoMessage()    {}
func (*CursorSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_770b178c3aab763f, []int{2}
}

func (m *CursorSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CursorSet.Unmarshal(m, b)
}
func (m *CursorSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CursorSet.Marshal(b, m, deterministic)
}
func (m *CursorSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CursorSet.Merge(m, src)
}
func (m *CursorSet) XXX_Size() int {
	return xxx_messageInfo_CursorSet.Size(m)
}
func (m *CursorSet) XXX_DiscardUnknown() {
	xxx_messageInfo_CursorSet.DiscardUnknown(m)
}

var xxx_messageInfo_CursorSet proto.InternalMessageInfo

func (m *CursorSet) GetCursors() []*Cursor {
	if m != nil {
		return m.Cursors
	}
	return nil
}

type Cursor struct {
	// Types that are valid to be assigned to Cursor:
	//	*Cursor_Offset
	//	*Cursor_Bytes
	Cursor               isCursor_Cursor `protobuf_oneof:"cursor"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Cursor) Reset()         { *m = Cursor{} }
func (m *Cursor) String() string { return proto.CompactTextString(m) }
func (*Cursor) ProtoMessage()    {}
func (*Cursor) Descriptor() ([]byte, []int) {
	return fileDescriptor_770b178c3aab763f, []int{3}
}

func (m *Cursor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cursor.Unmarshal(m, b)
}
func (m *Cursor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cursor.Marshal(b, m, deterministic)
}
func (m *Cursor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cursor.Merge(m, src)
}
func (m *Cursor) XXX_Size() int {
	return xxx_messageInfo_Cursor.Size(m)
}
func (m *Cursor) XXX_DiscardUnknown() {
	xxx_messageInfo_Cursor.DiscardUnknown(m)
}

var xxx_messageInfo_Cursor proto.InternalMessageInfo

type isCursor_Cursor interface {
	isCursor_Cursor()
}

type Cursor_Offset struct {
	Offset *OffsetCursor `protobuf:"bytes,1,opt,name=offset,proto3,oneof"`
}

type Cursor_Bytes struct {
	Bytes *BytesCursor `protobuf:"bytes,2,opt,name=bytes,proto3,oneof"`
}

func (*Cursor_Offset) isCursor_Cursor() {}

func (*Cursor_Bytes) isCursor_Cursor() {}

func (m *Cursor) GetCursor() isCursor_Cursor {
	if m != nil {
		return m.Cursor
	}
	return nil
}

func (m *Cursor) GetOffset() *OffsetCursor {
	if x, ok := m.GetCursor().(*Cursor_Offset); ok {
		return x.Offset
	}
	return nil
}

func (m *Cursor) GetBytes() *BytesCursor {
	if x, ok := m.GetCursor().(*Cursor_Bytes); ok {
		return x.Bytes
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Cursor) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Cursor_Offset)(nil),
		(*Cursor_Bytes)(nil),
	}
}

type OffsetCursor struct {
	Start                int64    `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64    `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OffsetCursor) Reset()         { *m = OffsetCursor{} }
func (m *OffsetCursor) String() string { return proto.CompactTextString(m) }
func (*OffsetCursor) ProtoMessage()    {}
func (*OffsetCursor) Descriptor() ([]byte, []int) {
	return fileDescriptor_770b178c3aab763f, []int{4}
}

func (m *OffsetCursor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OffsetCursor.Unmarshal(m, b)
}
func (m *OffsetCursor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OffsetCursor.Marshal(b, m, deterministic)
}
func (m *OffsetCursor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OffsetCursor.Merge(m, src)
}
func (m *OffsetCursor) XXX_Size() int {
	return xxx_messageInfo_OffsetCursor.Size(m)
}
func (m *OffsetCursor) XXX_DiscardUnknown() {
	xxx_messageInfo_OffsetCursor.DiscardUnknown(m)
}

var xxx_messageInfo_OffsetCursor proto.InternalMessageInfo

func (m *OffsetCursor) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *OffsetCursor) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

type BytesCursor struct {
	Start                []byte   `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  []byte   `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BytesCursor) Reset()         { *m = BytesCursor{} }
func (m *BytesCursor) String() string { return proto.CompactTextString(m) }
func (*BytesCursor) ProtoMessage()    {}
func (*BytesCursor) Descriptor() ([]byte, []int) {
	return fileDescriptor_770b178c3aab763f, []int{5}
}

func (m *BytesCursor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BytesCursor.Unmarshal(m, b)
}
func (m *BytesCursor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BytesCursor.Marshal(b, m, deterministic)
}
func (m *BytesCursor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BytesCursor.Merge(m, src)
}
func (m *BytesCursor) XXX_Size() int {
	return xxx_messageInfo_BytesCursor.Size(m)
}
func (m *BytesCursor) XXX_DiscardUnknown() {
	xxx_messageInfo_BytesCursor.DiscardUnknown(m)
}

var xxx_messageInfo_BytesCursor proto.InternalMessageInfo

func (m *BytesCursor) GetStart() []byte {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *BytesCursor) GetEnd() []byte {
	if m != nil {
		return m.End
	}
	return nil
}

func init() {
	proto.RegisterType((*Record)(nil), "proto.Record")
	proto.RegisterType((*WriteRecordsReport)(nil), "proto.WriteRecordsReport")
	proto.RegisterType((*CursorSet)(nil), "proto.CursorSet")
	proto.RegisterType((*Cursor)(nil), "proto.Cursor")
	proto.RegisterType((*OffsetCursor)(nil), "proto.OffsetCursor")
	proto.RegisterType((*BytesCursor)(nil), "proto.BytesCursor")
}

func init() { proto.RegisterFile("engine.proto", fileDescriptor_770b178c3aab763f) }

var fileDescriptor_770b178c3aab763f = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0xbf, 0x7c, 0x21, 0xb1, 0xbd, 0x89, 0xa0, 0xa3, 0x42, 0x40, 0xc1, 0x90, 0x4d, 0x83,
	0xd0, 0x2e, 0xea, 0x9f, 0x07, 0x48, 0x5d, 0xe8, 0xca, 0x32, 0x16, 0x5c, 0x86, 0x69, 0x73, 0xab,
	0xc1, 0x76, 0xa6, 0xcc, 0x5c, 0x15, 0x1f, 0xc0, 0xf7, 0x96, 0xcc, 0x24, 0x5a, 0xc5, 0x55, 0x72,
	0x7e, 0xf7, 0x9c, 0x73, 0x6f, 0x02, 0x31, 0xca, 0xc7, 0x5a, 0xe2, 0x68, 0xa3, 0x15, 0x29, 0x16,
	0xd8, 0x47, 0x36, 0x81, 0x90, 0xe3, 0x42, 0xe9, 0x8a, 0x1d, 0x43, 0x5f, 0xbc, 0x6a, 0x55, 0x56,
	0x82, 0x44, 0xe2, 0xa5, 0x5e, 0x1e, 0xf3, 0x5e, 0x03, 0xae, 0x05, 0x09, 0x76, 0x02, 0x7d, 0xaa,
	0xd7, 0x68, 0x48, 0xac, 0x37, 0xc9, 0xff, 0xd4, 0xcb, 0x7d, 0xfe, 0x0d, 0xb2, 0x0f, 0x0f, 0xd8,
	0x83, 0xae, 0x09, 0x5d, 0x95, 0xe1, 0xb8, 0x51, 0x9a, 0xd8, 0x29, 0x44, 0xb5, 0x34, 0x24, 0xe4,
	0x02, 0xcb, 0xba, 0x6a, 0x3b, 0xa1, 0x43, 0xb7, 0x15, 0x1b, 0x02, 0x43, 0xa1, 0x57, 0x35, 0x1a,
	0x2a, 0x7f, 0xd7, 0xef, 0x77, 0x93, 0x59, 0x37, 0x68, 0xfa, 0xe6, 0xef, 0x84, 0xa6, 0x24, 0x45,
	0x62, 0x95, 0xf8, 0xa9, 0x97, 0x07, 0x1c, 0x2c, 0x9a, 0x35, 0x24, 0xbb, 0x80, 0xfe, 0xe4, 0x45,
	0x1b, 0xa5, 0xef, 0x91, 0xd8, 0x00, 0x76, 0x16, 0x56, 0x98, 0xc4, 0x4b, 0xfd, 0x3c, 0x1a, 0xef,
	0xba, 0x2f, 0x1f, 0x39, 0x0b, 0xef, 0xa6, 0xd9, 0x1a, 0x42, 0x87, 0xd8, 0x10, 0x42, 0xb5, 0x5c,
	0x1a, 0x24, 0x7b, 0x6b, 0x34, 0x3e, 0x68, 0x13, 0x77, 0x16, 0x3a, 0xd3, 0xcd, 0x3f, 0xde, 0x9a,
	0xd8, 0x19, 0x04, 0x76, 0xb9, 0xbd, 0x38, 0x1a, 0xb3, 0xd6, 0x5d, 0x34, 0xec, 0xcb, 0xec, 0x2c,
	0x45, 0x0f, 0x42, 0xb7, 0x2f, 0xbb, 0x82, 0x78, 0xbb, 0x8f, 0x1d, 0x42, 0x60, 0x48, 0x68, 0xb7,
	0xd3, 0xe7, 0x4e, 0xb0, 0x3d, 0xf0, 0x51, 0x56, 0xed, 0xbf, 0x68, 0x5e, 0xb3, 0x4b, 0x88, 0xb6,
	0x9a, 0x7f, 0xc6, 0xe2, 0x3f, 0x62, 0xb1, 0x8d, 0x15, 0x03, 0x38, 0x92, 0x48, 0x6f, 0x4a, 0x3f,
	0x8f, 0xe6, 0x28, 0x51, 0xd0, 0x93, 0x3b, 0xb3, 0x88, 0x0b, 0x27, 0xa7, 0x8d, 0x9a, 0x7a, 0xf3,
	0xd0, 0xe2, 0xf3, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xa3, 0x08, 0x6d, 0x27, 0x02, 0x00,
	0x00,
}
