// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReadRecordsRequest struct {
	InstanceId           []byte   `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Where                string   `protobuf:"bytes,3,opt,name=where,proto3" json:"where,omitempty"`
	After                string   `protobuf:"bytes,4,opt,name=after,proto3" json:"after,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRecordsRequest) Reset()         { *m = ReadRecordsRequest{} }
func (m *ReadRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRecordsRequest) ProtoMessage()    {}
func (*ReadRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{0}
}

func (m *ReadRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRecordsRequest.Unmarshal(m, b)
}
func (m *ReadRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRecordsRequest.Marshal(b, m, deterministic)
}
func (m *ReadRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRecordsRequest.Merge(m, src)
}
func (m *ReadRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRecordsRequest.Size(m)
}
func (m *ReadRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRecordsRequest proto.InternalMessageInfo

func (m *ReadRecordsRequest) GetInstanceId() []byte {
	if m != nil {
		return m.InstanceId
	}
	return nil
}

func (m *ReadRecordsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ReadRecordsRequest) GetWhere() string {
	if m != nil {
		return m.Where
	}
	return ""
}

func (m *ReadRecordsRequest) GetAfter() string {
	if m != nil {
		return m.After
	}
	return ""
}

type ReadRecordsResponse struct {
	Records              []*Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReadRecordsResponse) Reset()         { *m = ReadRecordsResponse{} }
func (m *ReadRecordsResponse) String() string { return proto.CompactTextString(m) }
func (*ReadRecordsResponse) ProtoMessage()    {}
func (*ReadRecordsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{1}
}

func (m *ReadRecordsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRecordsResponse.Unmarshal(m, b)
}
func (m *ReadRecordsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRecordsResponse.Marshal(b, m, deterministic)
}
func (m *ReadRecordsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRecordsResponse.Merge(m, src)
}
func (m *ReadRecordsResponse) XXX_Size() int {
	return xxx_messageInfo_ReadRecordsResponse.Size(m)
}
func (m *ReadRecordsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRecordsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRecordsResponse proto.InternalMessageInfo

func (m *ReadRecordsResponse) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

type ReadLatestRecordsRequest struct {
	InstanceId           []byte   `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Before               int64    `protobuf:"varint,3,opt,name=before,proto3" json:"before,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadLatestRecordsRequest) Reset()         { *m = ReadLatestRecordsRequest{} }
func (m *ReadLatestRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*ReadLatestRecordsRequest) ProtoMessage()    {}
func (*ReadLatestRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{2}
}

func (m *ReadLatestRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadLatestRecordsRequest.Unmarshal(m, b)
}
func (m *ReadLatestRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadLatestRecordsRequest.Marshal(b, m, deterministic)
}
func (m *ReadLatestRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadLatestRecordsRequest.Merge(m, src)
}
func (m *ReadLatestRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_ReadLatestRecordsRequest.Size(m)
}
func (m *ReadLatestRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadLatestRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadLatestRecordsRequest proto.InternalMessageInfo

func (m *ReadLatestRecordsRequest) GetInstanceId() []byte {
	if m != nil {
		return m.InstanceId
	}
	return nil
}

func (m *ReadLatestRecordsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ReadLatestRecordsRequest) GetBefore() int64 {
	if m != nil {
		return m.Before
	}
	return 0
}

type WriteRecordsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteRecordsResponse) Reset()         { *m = WriteRecordsResponse{} }
func (m *WriteRecordsResponse) String() string { return proto.CompactTextString(m) }
func (*WriteRecordsResponse) ProtoMessage()    {}
func (*WriteRecordsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{3}
}

func (m *WriteRecordsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRecordsResponse.Unmarshal(m, b)
}
func (m *WriteRecordsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRecordsResponse.Marshal(b, m, deterministic)
}
func (m *WriteRecordsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRecordsResponse.Merge(m, src)
}
func (m *WriteRecordsResponse) XXX_Size() int {
	return xxx_messageInfo_WriteRecordsResponse.Size(m)
}
func (m *WriteRecordsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRecordsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRecordsResponse proto.InternalMessageInfo

type StreamDetailsRequest struct {
	ProjectName          string   `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	StreamName           string   `protobuf:"bytes,2,opt,name=stream_name,json=streamName,proto3" json:"stream_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamDetailsRequest) Reset()         { *m = StreamDetailsRequest{} }
func (m *StreamDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*StreamDetailsRequest) ProtoMessage()    {}
func (*StreamDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{4}
}

func (m *StreamDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamDetailsRequest.Unmarshal(m, b)
}
func (m *StreamDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamDetailsRequest.Marshal(b, m, deterministic)
}
func (m *StreamDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamDetailsRequest.Merge(m, src)
}
func (m *StreamDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_StreamDetailsRequest.Size(m)
}
func (m *StreamDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamDetailsRequest proto.InternalMessageInfo

func (m *StreamDetailsRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *StreamDetailsRequest) GetStreamName() string {
	if m != nil {
		return m.StreamName
	}
	return ""
}

type StreamDetailsResponse struct {
	CurrentInstanceId    []byte   `protobuf:"bytes,1,opt,name=current_instance_id,json=currentInstanceId,proto3" json:"current_instance_id,omitempty"`
	ProjectId            []byte   `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProjectName          string   `protobuf:"bytes,3,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	StreamName           string   `protobuf:"bytes,4,opt,name=stream_name,json=streamName,proto3" json:"stream_name,omitempty"`
	KeyFields            []string `protobuf:"bytes,5,rep,name=key_fields,json=keyFields,proto3" json:"key_fields,omitempty"`
	AvroSchema           string   `protobuf:"bytes,6,opt,name=avro_schema,json=avroSchema,proto3" json:"avro_schema,omitempty"`
	Public               bool     `protobuf:"varint,7,opt,name=public,proto3" json:"public,omitempty"`
	External             bool     `protobuf:"varint,8,opt,name=external,proto3" json:"external,omitempty"`
	Batch                bool     `protobuf:"varint,9,opt,name=batch,proto3" json:"batch,omitempty"`
	Manual               bool     `protobuf:"varint,10,opt,name=manual,proto3" json:"manual,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamDetailsResponse) Reset()         { *m = StreamDetailsResponse{} }
func (m *StreamDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*StreamDetailsResponse) ProtoMessage()    {}
func (*StreamDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{5}
}

func (m *StreamDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamDetailsResponse.Unmarshal(m, b)
}
func (m *StreamDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamDetailsResponse.Marshal(b, m, deterministic)
}
func (m *StreamDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamDetailsResponse.Merge(m, src)
}
func (m *StreamDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_StreamDetailsResponse.Size(m)
}
func (m *StreamDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamDetailsResponse proto.InternalMessageInfo

func (m *StreamDetailsResponse) GetCurrentInstanceId() []byte {
	if m != nil {
		return m.CurrentInstanceId
	}
	return nil
}

func (m *StreamDetailsResponse) GetProjectId() []byte {
	if m != nil {
		return m.ProjectId
	}
	return nil
}

func (m *StreamDetailsResponse) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *StreamDetailsResponse) GetStreamName() string {
	if m != nil {
		return m.StreamName
	}
	return ""
}

func (m *StreamDetailsResponse) GetKeyFields() []string {
	if m != nil {
		return m.KeyFields
	}
	return nil
}

func (m *StreamDetailsResponse) GetAvroSchema() string {
	if m != nil {
		return m.AvroSchema
	}
	return ""
}

func (m *StreamDetailsResponse) GetPublic() bool {
	if m != nil {
		return m.Public
	}
	return false
}

func (m *StreamDetailsResponse) GetExternal() bool {
	if m != nil {
		return m.External
	}
	return false
}

func (m *StreamDetailsResponse) GetBatch() bool {
	if m != nil {
		return m.Batch
	}
	return false
}

func (m *StreamDetailsResponse) GetManual() bool {
	if m != nil {
		return m.Manual
	}
	return false
}

type PackageVersionRequest struct {
	PackageVersion       string   `protobuf:"bytes,1,opt,name=package_version,json=packageVersion,proto3" json:"package_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PackageVersionRequest) Reset()         { *m = PackageVersionRequest{} }
func (m *PackageVersionRequest) String() string { return proto.CompactTextString(m) }
func (*PackageVersionRequest) ProtoMessage()    {}
func (*PackageVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{6}
}

func (m *PackageVersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackageVersionRequest.Unmarshal(m, b)
}
func (m *PackageVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackageVersionRequest.Marshal(b, m, deterministic)
}
func (m *PackageVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageVersionRequest.Merge(m, src)
}
func (m *PackageVersionRequest) XXX_Size() int {
	return xxx_messageInfo_PackageVersionRequest.Size(m)
}
func (m *PackageVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PackageVersionRequest proto.InternalMessageInfo

func (m *PackageVersionRequest) GetPackageVersion() string {
	if m != nil {
		return m.PackageVersion
	}
	return ""
}

type PackageVersionResponse struct {
	VersionResponse      string   `protobuf:"bytes,1,opt,name=version_response,json=versionResponse,proto3" json:"version_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PackageVersionResponse) Reset()         { *m = PackageVersionResponse{} }
func (m *PackageVersionResponse) String() string { return proto.CompactTextString(m) }
func (*PackageVersionResponse) ProtoMessage()    {}
func (*PackageVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{7}
}

func (m *PackageVersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackageVersionResponse.Unmarshal(m, b)
}
func (m *PackageVersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackageVersionResponse.Marshal(b, m, deterministic)
}
func (m *PackageVersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageVersionResponse.Merge(m, src)
}
func (m *PackageVersionResponse) XXX_Size() int {
	return xxx_messageInfo_PackageVersionResponse.Size(m)
}
func (m *PackageVersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageVersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PackageVersionResponse proto.InternalMessageInfo

func (m *PackageVersionResponse) GetVersionResponse() string {
	if m != nil {
		return m.VersionResponse
	}
	return ""
}

func init() {
	proto.RegisterType((*ReadRecordsRequest)(nil), "proto.ReadRecordsRequest")
	proto.RegisterType((*ReadRecordsResponse)(nil), "proto.ReadRecordsResponse")
	proto.RegisterType((*ReadLatestRecordsRequest)(nil), "proto.ReadLatestRecordsRequest")
	proto.RegisterType((*WriteRecordsResponse)(nil), "proto.WriteRecordsResponse")
	proto.RegisterType((*StreamDetailsRequest)(nil), "proto.StreamDetailsRequest")
	proto.RegisterType((*StreamDetailsResponse)(nil), "proto.StreamDetailsResponse")
	proto.RegisterType((*PackageVersionRequest)(nil), "proto.PackageVersionRequest")
	proto.RegisterType((*PackageVersionResponse)(nil), "proto.PackageVersionResponse")
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor_f1a937782ebbded5) }

var fileDescriptor_f1a937782ebbded5 = []byte{
	// 589 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4f, 0x4f, 0xdb, 0x4e,
	0x10, 0xfd, 0x99, 0x10, 0x20, 0x93, 0xf0, 0x03, 0x96, 0x3f, 0xda, 0xa6, 0x45, 0xa4, 0xbe, 0xe0,
	0x5e, 0x72, 0xa0, 0xf7, 0xaa, 0x82, 0x0a, 0x14, 0xa9, 0x6a, 0xd1, 0x22, 0xb5, 0x52, 0x2f, 0xee,
	0xc6, 0x1e, 0xc8, 0x36, 0xf6, 0xda, 0x5d, 0x6f, 0x48, 0xf9, 0x3c, 0xfd, 0x3a, 0xfd, 0x50, 0xd5,
	0x7a, 0xd7, 0x29, 0x4e, 0x5c, 0x71, 0xe9, 0xc9, 0x9a, 0xf7, 0x66, 0xde, 0x3c, 0xef, 0xcc, 0xc0,
	0xf6, 0x1d, 0xd7, 0x38, 0xe7, 0x0f, 0xc3, 0x5c, 0x65, 0x3a, 0x23, 0xed, 0xf2, 0xd3, 0xef, 0xa1,
	0xbc, 0x13, 0x12, 0x2d, 0xe8, 0xcf, 0x81, 0x30, 0xe4, 0x31, 0xc3, 0x28, 0x53, 0x71, 0xc1, 0xf0,
	0xfb, 0x0c, 0x0b, 0x4d, 0x4e, 0xa0, 0x2b, 0x64, 0xa1, 0xb9, 0x8c, 0x30, 0x14, 0x31, 0xf5, 0x06,
	0x5e, 0xd0, 0x63, 0x50, 0x41, 0xa3, 0x98, 0x1c, 0x40, 0x3b, 0x11, 0xa9, 0xd0, 0x74, 0x6d, 0xe0,
	0x05, 0x6d, 0x66, 0x03, 0x83, 0xce, 0x27, 0xa8, 0x90, 0xb6, 0x06, 0x5e, 0xd0, 0x61, 0x36, 0x30,
	0x28, 0xbf, 0xd5, 0xa8, 0xe8, 0xba, 0x45, 0xcb, 0xc0, 0x7f, 0x03, 0xfb, 0xb5, 0xc6, 0x45, 0x9e,
	0xc9, 0x02, 0xc9, 0x29, 0x6c, 0x2a, 0x0b, 0x51, 0x6f, 0xd0, 0x0a, 0xba, 0x67, 0xdb, 0xd6, 0xe8,
	0xd0, 0x26, 0xb2, 0x8a, 0xf5, 0x05, 0x50, 0x53, 0xff, 0x9e, 0x6b, 0x2c, 0xf4, 0xbf, 0xb1, 0x7f,
	0x04, 0x1b, 0x63, 0xbc, 0xcd, 0x9c, 0xff, 0x16, 0x73, 0x91, 0x7f, 0x04, 0x07, 0x9f, 0x95, 0xd0,
	0xb8, 0xe4, 0xd5, 0xff, 0x02, 0x07, 0x37, 0x5a, 0x21, 0x4f, 0xdf, 0xa1, 0xe6, 0x22, 0x59, 0xb4,
	0x7f, 0x09, 0xbd, 0x5c, 0x65, 0xdf, 0x30, 0xd2, 0xa1, 0xe4, 0x29, 0x96, 0xfd, 0x3b, 0xac, 0xeb,
	0xb0, 0x0f, 0x3c, 0x45, 0xe3, 0xb0, 0x28, 0x4b, 0x6d, 0xc6, 0x5a, 0x99, 0x01, 0x16, 0x32, 0x09,
	0xfe, 0xaf, 0x35, 0x38, 0x5c, 0x12, 0x77, 0x2f, 0x34, 0x84, 0xfd, 0x68, 0xa6, 0x14, 0x4a, 0x1d,
	0xae, 0xfe, 0xe4, 0x9e, 0xa3, 0x46, 0x7f, 0xfe, 0xf5, 0x18, 0xa0, 0x72, 0x23, 0xe2, 0xb2, 0x53,
	0x8f, 0x75, 0x1c, 0x32, 0x8a, 0x57, 0xcc, 0xb6, 0x9e, 0x34, 0xbb, 0xbe, 0x6c, 0xd6, 0xb4, 0x98,
	0xe2, 0x43, 0x78, 0x2b, 0x30, 0x89, 0x0b, 0xda, 0x1e, 0xb4, 0x82, 0x0e, 0xeb, 0x4c, 0xf1, 0xe1,
	0xb2, 0x04, 0x4c, 0x3d, 0xbf, 0x57, 0x59, 0x58, 0x44, 0x13, 0x4c, 0x39, 0xdd, 0xb0, 0xf5, 0x06,
	0xba, 0x29, 0x11, 0xf3, 0xf0, 0xf9, 0x6c, 0x9c, 0x88, 0x88, 0x6e, 0x0e, 0xbc, 0x60, 0x8b, 0xb9,
	0x88, 0xf4, 0x61, 0x0b, 0x7f, 0x68, 0x54, 0x92, 0x27, 0x74, 0xab, 0x64, 0x16, 0xb1, 0x19, 0xe1,
	0x98, 0xeb, 0x68, 0x42, 0x3b, 0x25, 0x61, 0x03, 0xa3, 0x94, 0x72, 0x39, 0xe3, 0x09, 0x05, 0xab,
	0x64, 0x23, 0xff, 0x2d, 0x1c, 0x5e, 0xf3, 0x68, 0xca, 0xef, 0xf0, 0x13, 0xaa, 0x42, 0x64, 0xb2,
	0x9a, 0xd5, 0x29, 0xec, 0xe4, 0x96, 0x08, 0xef, 0x2d, 0xe3, 0xc6, 0xf5, 0x7f, 0x5e, 0xcb, 0xf7,
	0x2f, 0xe0, 0x68, 0x59, 0xc1, 0x0d, 0xe4, 0x15, 0xec, 0xba, 0xd2, 0x50, 0x39, 0xcc, 0x69, 0xec,
	0xdc, 0xd7, 0x53, 0xcf, 0x7e, 0xb6, 0x60, 0xf3, 0xca, 0x1e, 0x25, 0xb9, 0x84, 0xee, 0xa3, 0x03,
	0x20, 0xcf, 0x16, 0x7b, 0xbe, 0x7c, 0x8d, 0xfd, 0x7e, 0x13, 0xe5, 0x76, 0xf0, 0x3f, 0xc2, 0x60,
	0x6f, 0xe5, 0x10, 0xc8, 0xc9, 0xa3, 0x92, 0xa6, 0x13, 0x79, 0x42, 0x73, 0x04, 0xbd, 0xc7, 0x1b,
	0x4f, 0xaa, 0xec, 0xfa, 0x19, 0x58, 0xa5, 0xe7, 0x8d, 0xdc, 0x42, 0xea, 0x23, 0xec, 0x5e, 0xa1,
	0xae, 0xad, 0x32, 0xa9, 0x4a, 0x9a, 0xae, 0xa7, 0xff, 0xa2, 0x99, 0x5c, 0x08, 0x7e, 0x85, 0x93,
	0x2b, 0xd4, 0x17, 0x76, 0xcf, 0xcf, 0x51, 0x22, 0xd7, 0x93, 0xfa, 0x64, 0x48, 0x25, 0xd1, 0x38,
	0xf2, 0xfe, 0xf1, 0x5f, 0xd8, 0xaa, 0xc3, 0xf9, 0x29, 0x1c, 0x4a, 0xd4, 0xf3, 0x4c, 0x4d, 0x87,
	0x63, 0xab, 0x6f, 0x2b, 0xce, 0x7b, 0x55, 0x3b, 0x13, 0x5d, 0x7b, 0xe3, 0x8d, 0x12, 0x7e, 0xfd,
	0x3b, 0x00, 0x00, 0xff, 0xff, 0x83, 0xed, 0x7d, 0x47, 0x69, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GatewayClient is the client API for Gateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GatewayClient interface {
	ReadRecords(ctx context.Context, in *ReadRecordsRequest, opts ...grpc.CallOption) (*ReadRecordsResponse, error)
	ReadLatestRecords(ctx context.Context, in *ReadLatestRecordsRequest, opts ...grpc.CallOption) (*ReadRecordsResponse, error)
	WriteRecords(ctx context.Context, in *WriteRecordsRequest, opts ...grpc.CallOption) (*WriteRecordsResponse, error)
	GetStreamDetails(ctx context.Context, in *StreamDetailsRequest, opts ...grpc.CallOption) (*StreamDetailsResponse, error)
	GetCurrentBeneathPackageVersion(ctx context.Context, in *PackageVersionRequest, opts ...grpc.CallOption) (*PackageVersionResponse, error)
}

type gatewayClient struct {
	cc *grpc.ClientConn
}

func NewGatewayClient(cc *grpc.ClientConn) GatewayClient {
	return &gatewayClient{cc}
}

func (c *gatewayClient) ReadRecords(ctx context.Context, in *ReadRecordsRequest, opts ...grpc.CallOption) (*ReadRecordsResponse, error) {
	out := new(ReadRecordsResponse)
	err := c.cc.Invoke(ctx, "/proto.Gateway/ReadRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) ReadLatestRecords(ctx context.Context, in *ReadLatestRecordsRequest, opts ...grpc.CallOption) (*ReadRecordsResponse, error) {
	out := new(ReadRecordsResponse)
	err := c.cc.Invoke(ctx, "/proto.Gateway/ReadLatestRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) WriteRecords(ctx context.Context, in *WriteRecordsRequest, opts ...grpc.CallOption) (*WriteRecordsResponse, error) {
	out := new(WriteRecordsResponse)
	err := c.cc.Invoke(ctx, "/proto.Gateway/WriteRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) GetStreamDetails(ctx context.Context, in *StreamDetailsRequest, opts ...grpc.CallOption) (*StreamDetailsResponse, error) {
	out := new(StreamDetailsResponse)
	err := c.cc.Invoke(ctx, "/proto.Gateway/GetStreamDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) GetCurrentBeneathPackageVersion(ctx context.Context, in *PackageVersionRequest, opts ...grpc.CallOption) (*PackageVersionResponse, error) {
	out := new(PackageVersionResponse)
	err := c.cc.Invoke(ctx, "/proto.Gateway/GetCurrentBeneathPackageVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServer is the server API for Gateway service.
type GatewayServer interface {
	ReadRecords(context.Context, *ReadRecordsRequest) (*ReadRecordsResponse, error)
	ReadLatestRecords(context.Context, *ReadLatestRecordsRequest) (*ReadRecordsResponse, error)
	WriteRecords(context.Context, *WriteRecordsRequest) (*WriteRecordsResponse, error)
	GetStreamDetails(context.Context, *StreamDetailsRequest) (*StreamDetailsResponse, error)
	GetCurrentBeneathPackageVersion(context.Context, *PackageVersionRequest) (*PackageVersionResponse, error)
}

// UnimplementedGatewayServer can be embedded to have forward compatible implementations.
type UnimplementedGatewayServer struct {
}

func (*UnimplementedGatewayServer) ReadRecords(ctx context.Context, req *ReadRecordsRequest) (*ReadRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadRecords not implemented")
}
func (*UnimplementedGatewayServer) ReadLatestRecords(ctx context.Context, req *ReadLatestRecordsRequest) (*ReadRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadLatestRecords not implemented")
}
func (*UnimplementedGatewayServer) WriteRecords(ctx context.Context, req *WriteRecordsRequest) (*WriteRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteRecords not implemented")
}
func (*UnimplementedGatewayServer) GetStreamDetails(ctx context.Context, req *StreamDetailsRequest) (*StreamDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStreamDetails not implemented")
}
func (*UnimplementedGatewayServer) GetCurrentBeneathPackageVersion(ctx context.Context, req *PackageVersionRequest) (*PackageVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentBeneathPackageVersion not implemented")
}

func RegisterGatewayServer(s *grpc.Server, srv GatewayServer) {
	s.RegisterService(&_Gateway_serviceDesc, srv)
}

func _Gateway_ReadRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).ReadRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Gateway/ReadRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).ReadRecords(ctx, req.(*ReadRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_ReadLatestRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadLatestRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).ReadLatestRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Gateway/ReadLatestRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).ReadLatestRecords(ctx, req.(*ReadLatestRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_WriteRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).WriteRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Gateway/WriteRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).WriteRecords(ctx, req.(*WriteRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_GetStreamDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).GetStreamDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Gateway/GetStreamDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).GetStreamDetails(ctx, req.(*StreamDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_GetCurrentBeneathPackageVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).GetCurrentBeneathPackageVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Gateway/GetCurrentBeneathPackageVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).GetCurrentBeneathPackageVersion(ctx, req.(*PackageVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Gateway",
	HandlerType: (*GatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadRecords",
			Handler:    _Gateway_ReadRecords_Handler,
		},
		{
			MethodName: "ReadLatestRecords",
			Handler:    _Gateway_ReadLatestRecords_Handler,
		},
		{
			MethodName: "WriteRecords",
			Handler:    _Gateway_WriteRecords_Handler,
		},
		{
			MethodName: "GetStreamDetails",
			Handler:    _Gateway_GetStreamDetails_Handler,
		},
		{
			MethodName: "GetCurrentBeneathPackageVersion",
			Handler:    _Gateway_GetCurrentBeneathPackageVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}
