// Code generated by protoc-gen-go. DO NOT EDIT.
// source: quota.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QuotaUsage struct {
	ReadOps              int64    `protobuf:"varint,1,opt,name=read_ops,json=readOps,proto3" json:"read_ops,omitempty"`
	ReadRecords          int64    `protobuf:"varint,2,opt,name=read_records,json=readRecords,proto3" json:"read_records,omitempty"`
	ReadBytes            int64    `protobuf:"varint,3,opt,name=read_bytes,json=readBytes,proto3" json:"read_bytes,omitempty"`
	WriteOps             int64    `protobuf:"varint,4,opt,name=write_ops,json=writeOps,proto3" json:"write_ops,omitempty"`
	WriteRecords         int64    `protobuf:"varint,5,opt,name=write_records,json=writeRecords,proto3" json:"write_records,omitempty"`
	WriteBytes           int64    `protobuf:"varint,6,opt,name=write_bytes,json=writeBytes,proto3" json:"write_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuotaUsage) Reset()         { *m = QuotaUsage{} }
func (m *QuotaUsage) String() string { return proto.CompactTextString(m) }
func (*QuotaUsage) ProtoMessage()    {}
func (*QuotaUsage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3d42a6e345ff44a, []int{0}
}

func (m *QuotaUsage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuotaUsage.Unmarshal(m, b)
}
func (m *QuotaUsage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuotaUsage.Marshal(b, m, deterministic)
}
func (m *QuotaUsage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuotaUsage.Merge(m, src)
}
func (m *QuotaUsage) XXX_Size() int {
	return xxx_messageInfo_QuotaUsage.Size(m)
}
func (m *QuotaUsage) XXX_DiscardUnknown() {
	xxx_messageInfo_QuotaUsage.DiscardUnknown(m)
}

var xxx_messageInfo_QuotaUsage proto.InternalMessageInfo

func (m *QuotaUsage) GetReadOps() int64 {
	if m != nil {
		return m.ReadOps
	}
	return 0
}

func (m *QuotaUsage) GetReadRecords() int64 {
	if m != nil {
		return m.ReadRecords
	}
	return 0
}

func (m *QuotaUsage) GetReadBytes() int64 {
	if m != nil {
		return m.ReadBytes
	}
	return 0
}

func (m *QuotaUsage) GetWriteOps() int64 {
	if m != nil {
		return m.WriteOps
	}
	return 0
}

func (m *QuotaUsage) GetWriteRecords() int64 {
	if m != nil {
		return m.WriteRecords
	}
	return 0
}

func (m *QuotaUsage) GetWriteBytes() int64 {
	if m != nil {
		return m.WriteBytes
	}
	return 0
}

func init() {
	proto.RegisterType((*QuotaUsage)(nil), "proto.QuotaUsage")
}

func init() { proto.RegisterFile("quota.proto", fileDescriptor_d3d42a6e345ff44a) }

var fileDescriptor_d3d42a6e345ff44a = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0x4d, 0x0a, 0xc2, 0x30,
	0x10, 0x85, 0x89, 0xb5, 0xb5, 0x9d, 0xd6, 0x4d, 0x40, 0xa8, 0x88, 0xf8, 0xb7, 0xd0, 0x55, 0x37,
	0xde, 0x20, 0x17, 0xb0, 0x16, 0x5c, 0x4b, 0x6a, 0x07, 0x15, 0xa1, 0xa9, 0x49, 0xa4, 0x78, 0x47,
	0x0f, 0x25, 0x99, 0xd0, 0x55, 0x98, 0xef, 0x7d, 0xbc, 0x47, 0x20, 0x7d, 0x7f, 0x94, 0x95, 0x45,
	0xa7, 0x95, 0x55, 0x3c, 0xa4, 0x67, 0xfb, 0x63, 0x00, 0x67, 0x87, 0x2f, 0x46, 0xde, 0x91, 0xcf,
	0x21, 0xd6, 0x28, 0x9b, 0xab, 0xea, 0x4c, 0xce, 0xd6, 0xec, 0x10, 0x54, 0x13, 0x77, 0x9f, 0x3a,
	0xc3, 0x37, 0x90, 0x51, 0xa4, 0xf1, 0xa6, 0x74, 0x63, 0xf2, 0x11, 0xc5, 0xa9, 0x63, 0x95, 0x47,
	0x7c, 0x09, 0x40, 0x4a, 0xfd, 0xb5, 0x68, 0xf2, 0x80, 0x84, 0xc4, 0x11, 0xe1, 0x00, 0x5f, 0x40,
	0xd2, 0xeb, 0xa7, 0x45, 0x6a, 0x1f, 0x53, 0x1a, 0x13, 0x70, 0xf5, 0x3b, 0x98, 0xfa, 0x70, 0xe8,
	0x0f, 0x49, 0xc8, 0x08, 0x0e, 0x03, 0x2b, 0x48, 0xbd, 0xe4, 0x17, 0x22, 0x52, 0x80, 0x10, 0x4d,
	0x88, 0x3d, 0xcc, 0x5a, 0xb4, 0xbd, 0xd2, 0xaf, 0xa2, 0xc6, 0x16, 0xa5, 0x7d, 0xf8, 0xef, 0x8a,
	0x4c, 0xf8, 0xb3, 0x74, 0x57, 0xc9, 0xea, 0x88, 0xf0, 0xf1, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xcf,
	0x04, 0x1b, 0xb1, 0x14, 0x01, 0x00, 0x00,
}
