// Code generated by protoc-gen-go. DO NOT EDIT.
// source: engine/proto/taskqueue.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueuedTask struct {
	UniqueId             string   `protobuf:"bytes,1,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueuedTask) Reset()         { *m = QueuedTask{} }
func (m *QueuedTask) String() string { return proto.CompactTextString(m) }
func (*QueuedTask) ProtoMessage()    {}
func (*QueuedTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d8e4fa168af5ca, []int{0}
}

func (m *QueuedTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueuedTask.Unmarshal(m, b)
}
func (m *QueuedTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueuedTask.Marshal(b, m, deterministic)
}
func (m *QueuedTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueuedTask.Merge(m, src)
}
func (m *QueuedTask) XXX_Size() int {
	return xxx_messageInfo_QueuedTask.Size(m)
}
func (m *QueuedTask) XXX_DiscardUnknown() {
	xxx_messageInfo_QueuedTask.DiscardUnknown(m)
}

var xxx_messageInfo_QueuedTask proto.InternalMessageInfo

func (m *QueuedTask) GetUniqueId() string {
	if m != nil {
		return m.UniqueId
	}
	return ""
}

func (m *QueuedTask) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *QueuedTask) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *QueuedTask) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*QueuedTask)(nil), "engine.QueuedTask")
}

func init() { proto.RegisterFile("engine/proto/taskqueue.proto", fileDescriptor_51d8e4fa168af5ca) }

var fileDescriptor_51d8e4fa168af5ca = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xce, 0xbf, 0xab, 0x83, 0x30,
	0x10, 0x07, 0x70, 0xf2, 0x14, 0x79, 0x86, 0x37, 0x65, 0x0a, 0x3c, 0x07, 0xe9, 0xe4, 0x52, 0x43,
	0xe9, 0x7f, 0xd0, 0xad, 0x63, 0xa5, 0x53, 0x97, 0x72, 0x9a, 0x43, 0x83, 0x24, 0xf1, 0xc7, 0xe5,
	0xff, 0x2f, 0x46, 0x68, 0x3b, 0xdd, 0xf7, 0xfb, 0x39, 0x0e, 0x8e, 0x17, 0xe8, 0x7a, 0xe3, 0x50,
	0x4d, 0x8b, 0x27, 0xaf, 0x08, 0xd6, 0x71, 0x0e, 0x18, 0xb0, 0x8e, 0x5d, 0x64, 0xfb, 0xf6, 0xe0,
	0x39, 0xbf, 0x6d, 0xac, 0xef, 0xb0, 0x8e, 0xe2, 0x9f, 0xe7, 0xc1, 0x99, 0x39, 0xe0, 0xd3, 0x68,
	0xc9, 0x4a, 0x56, 0xe5, 0xcd, 0xef, 0x0e, 0x57, 0x2d, 0x04, 0x4f, 0x1d, 0x58, 0x94, 0x3f, 0xd1,
	0x63, 0x16, 0x05, 0xcf, 0xc9, 0x58, 0x5c, 0x09, 0xec, 0x24, 0x93, 0x92, 0x55, 0x49, 0xf3, 0x81,
	0xed, 0x42, 0x03, 0x81, 0x4c, 0x4b, 0x56, 0xfd, 0x35, 0x31, 0x5f, 0x4e, 0x0f, 0xd5, 0x1b, 0x1a,
	0x42, 0x5b, 0x77, 0xde, 0xaa, 0x16, 0x1d, 0x02, 0x0d, 0xc7, 0xce, 0x2f, 0xf8, 0x2e, 0xbd, 0x57,
	0xdf, 0xbf, 0xb7, 0x59, 0x1c, 0xe7, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x7d, 0x12, 0xcc,
	0xd2, 0x00, 0x00, 0x00,
}
