// Code generated by protoc-gen-go. DO NOT EDIT.
// source: engine/driver/bigtable/proto/cursor.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Cursor_Type int32

const (
	Cursor_LOG   Cursor_Type = 0
	Cursor_INDEX Cursor_Type = 1
)

var Cursor_Type_name = map[int32]string{
	0: "LOG",
	1: "INDEX",
}

var Cursor_Type_value = map[string]int32{
	"LOG":   0,
	"INDEX": 1,
}

func (x Cursor_Type) String() string {
	return proto.EnumName(Cursor_Type_name, int32(x))
}

func (Cursor_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_09dade45cc45a2f4, []int{1, 0}
}

type CursorSet struct {
	Cursors              []*Cursor `protobuf:"bytes,1,rep,name=cursors,proto3" json:"cursors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CursorSet) Reset()         { *m = CursorSet{} }
func (m *CursorSet) String() string { return proto.CompactTextString(m) }
func (*CursorSet) ProtoMessage()    {}
func (*CursorSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_09dade45cc45a2f4, []int{0}
}

func (m *CursorSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CursorSet.Unmarshal(m, b)
}
func (m *CursorSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CursorSet.Marshal(b, m, deterministic)
}
func (m *CursorSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CursorSet.Merge(m, src)
}
func (m *CursorSet) XXX_Size() int {
	return xxx_messageInfo_CursorSet.Size(m)
}
func (m *CursorSet) XXX_DiscardUnknown() {
	xxx_messageInfo_CursorSet.DiscardUnknown(m)
}

var xxx_messageInfo_CursorSet proto.InternalMessageInfo

func (m *CursorSet) GetCursors() []*Cursor {
	if m != nil {
		return m.Cursors
	}
	return nil
}

type Cursor struct {
	Type                 Cursor_Type `protobuf:"varint,1,opt,name=type,proto3,enum=bigtable.Cursor_Type" json:"type,omitempty"`
	LogStart             int64       `protobuf:"varint,10,opt,name=log_start,json=logStart,proto3" json:"log_start,omitempty"`
	LogEnd               int64       `protobuf:"varint,11,opt,name=log_end,json=logEnd,proto3" json:"log_end,omitempty"`
	IndexId              int32       `protobuf:"varint,20,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	IndexStart           []byte      `protobuf:"bytes,21,opt,name=index_start,json=indexStart,proto3" json:"index_start,omitempty"`
	IndexEnd             []byte      `protobuf:"bytes,22,opt,name=index_end,json=indexEnd,proto3" json:"index_end,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Cursor) Reset()         { *m = Cursor{} }
func (m *Cursor) String() string { return proto.CompactTextString(m) }
func (*Cursor) ProtoMessage()    {}
func (*Cursor) Descriptor() ([]byte, []int) {
	return fileDescriptor_09dade45cc45a2f4, []int{1}
}

func (m *Cursor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cursor.Unmarshal(m, b)
}
func (m *Cursor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cursor.Marshal(b, m, deterministic)
}
func (m *Cursor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cursor.Merge(m, src)
}
func (m *Cursor) XXX_Size() int {
	return xxx_messageInfo_Cursor.Size(m)
}
func (m *Cursor) XXX_DiscardUnknown() {
	xxx_messageInfo_Cursor.DiscardUnknown(m)
}

var xxx_messageInfo_Cursor proto.InternalMessageInfo

func (m *Cursor) GetType() Cursor_Type {
	if m != nil {
		return m.Type
	}
	return Cursor_LOG
}

func (m *Cursor) GetLogStart() int64 {
	if m != nil {
		return m.LogStart
	}
	return 0
}

func (m *Cursor) GetLogEnd() int64 {
	if m != nil {
		return m.LogEnd
	}
	return 0
}

func (m *Cursor) GetIndexId() int32 {
	if m != nil {
		return m.IndexId
	}
	return 0
}

func (m *Cursor) GetIndexStart() []byte {
	if m != nil {
		return m.IndexStart
	}
	return nil
}

func (m *Cursor) GetIndexEnd() []byte {
	if m != nil {
		return m.IndexEnd
	}
	return nil
}

func init() {
	proto.RegisterEnum("bigtable.Cursor_Type", Cursor_Type_name, Cursor_Type_value)
	proto.RegisterType((*CursorSet)(nil), "bigtable.CursorSet")
	proto.RegisterType((*Cursor)(nil), "bigtable.Cursor")
}

func init() {
	proto.RegisterFile("engine/driver/bigtable/proto/cursor.proto", fileDescriptor_09dade45cc45a2f4)
}

var fileDescriptor_09dade45cc45a2f4 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcf, 0x4a, 0xec, 0x30,
	0x1c, 0x85, 0x6f, 0xe8, 0xf4, 0xdf, 0xaf, 0x17, 0x29, 0xc1, 0xd1, 0xea, 0x2c, 0x2c, 0x5d, 0x65,
	0x5c, 0xb4, 0x30, 0x2e, 0xdc, 0xab, 0x45, 0x06, 0x44, 0x21, 0xe3, 0x42, 0xdc, 0x0c, 0x53, 0x13,
	0x42, 0xa0, 0x24, 0x25, 0x8d, 0xe2, 0xbc, 0xac, 0xcf, 0x22, 0x4d, 0xe8, 0xc6, 0x55, 0x38, 0xe7,
	0xfb, 0x72, 0x08, 0x81, 0x35, 0x57, 0x42, 0x2a, 0xde, 0x30, 0x23, 0xbf, 0xb8, 0x69, 0x3a, 0x29,
	0xec, 0xa1, 0xeb, 0x79, 0x33, 0x18, 0x6d, 0x75, 0xf3, 0xf1, 0x69, 0x46, 0x6d, 0x6a, 0x17, 0x70,
	0x32, 0xc3, 0xea, 0x16, 0xd2, 0x7b, 0x47, 0x76, 0xdc, 0xe2, 0x6b, 0x88, 0xbd, 0x36, 0x16, 0xa8,
	0x0c, 0x48, 0xb6, 0xc9, 0xeb, 0x59, 0xac, 0xbd, 0x45, 0x67, 0xa1, 0xfa, 0x41, 0x10, 0xf9, 0x0e,
	0xaf, 0x61, 0x61, 0x8f, 0x03, 0x2f, 0x50, 0x89, 0xc8, 0xc9, 0x66, 0xf9, 0xf7, 0x4e, 0xfd, 0x7a,
	0x1c, 0x38, 0x75, 0x0a, 0x5e, 0x41, 0xda, 0x6b, 0xb1, 0x1f, 0xed, 0xc1, 0xd8, 0x02, 0x4a, 0x44,
	0x02, 0x9a, 0xf4, 0x5a, 0xec, 0xa6, 0x8c, 0xcf, 0x21, 0x9e, 0x20, 0x57, 0xac, 0xc8, 0x1c, 0x8a,
	0x7a, 0x2d, 0x5a, 0xc5, 0xf0, 0x05, 0x24, 0x52, 0x31, 0xfe, 0xbd, 0x97, 0xac, 0x38, 0x2d, 0x11,
	0x09, 0x69, 0xec, 0xf2, 0x96, 0xe1, 0x2b, 0xc8, 0x3c, 0xf2, 0x93, 0xcb, 0x12, 0x91, 0xff, 0x14,
	0x5c, 0xe5, 0x47, 0x57, 0x90, 0x7a, 0x61, 0x9a, 0x3d, 0x73, 0xd8, 0x8f, 0xb5, 0x8a, 0x55, 0x97,
	0xb0, 0x98, 0x1e, 0x87, 0x63, 0x08, 0x9e, 0x5e, 0x1e, 0xf3, 0x7f, 0x38, 0x85, 0x70, 0xfb, 0xfc,
	0xd0, 0xbe, 0xe5, 0xe8, 0x2e, 0x7e, 0x0f, 0xdd, 0x67, 0x75, 0x91, 0x3b, 0x6e, 0x7e, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x22, 0x97, 0xdf, 0x79, 0x60, 0x01, 0x00, 0x00,
}
