// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WriteRecordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteRecordResponse) Reset()         { *m = WriteRecordResponse{} }
func (m *WriteRecordResponse) String() string { return proto.CompactTextString(m) }
func (*WriteRecordResponse) ProtoMessage()    {}
func (*WriteRecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{0}
}

func (m *WriteRecordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRecordResponse.Unmarshal(m, b)
}
func (m *WriteRecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRecordResponse.Marshal(b, m, deterministic)
}
func (m *WriteRecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRecordResponse.Merge(m, src)
}
func (m *WriteRecordResponse) XXX_Size() int {
	return xxx_messageInfo_WriteRecordResponse.Size(m)
}
func (m *WriteRecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRecordResponse proto.InternalMessageInfo

type WriteRecordsRequest struct {
	InstanceId           []byte    `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Records              []*Record `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *WriteRecordsRequest) Reset()         { *m = WriteRecordsRequest{} }
func (m *WriteRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*WriteRecordsRequest) ProtoMessage()    {}
func (*WriteRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{1}
}

func (m *WriteRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRecordsRequest.Unmarshal(m, b)
}
func (m *WriteRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRecordsRequest.Marshal(b, m, deterministic)
}
func (m *WriteRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRecordsRequest.Merge(m, src)
}
func (m *WriteRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_WriteRecordsRequest.Size(m)
}
func (m *WriteRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRecordsRequest proto.InternalMessageInfo

func (m *WriteRecordsRequest) GetInstanceId() []byte {
	if m != nil {
		return m.InstanceId
	}
	return nil
}

func (m *WriteRecordsRequest) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

type Record struct {
	SequenceNumber       []byte   `protobuf:"bytes,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	AvroData             []byte   `protobuf:"bytes,3,opt,name=avro_data,json=avroData,proto3" json:"avro_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{2}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetSequenceNumber() []byte {
	if m != nil {
		return m.SequenceNumber
	}
	return nil
}

func (m *Record) GetAvroData() []byte {
	if m != nil {
		return m.AvroData
	}
	return nil
}

func init() {
	proto.RegisterType((*WriteRecordResponse)(nil), "proto.WriteRecordResponse")
	proto.RegisterType((*WriteRecordsRequest)(nil), "proto.WriteRecordsRequest")
	proto.RegisterType((*Record)(nil), "proto.Record")
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor_f1a937782ebbded5) }

var fileDescriptor_f1a937782ebbded5 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0x87, 0xdd, 0x16, 0x5b, 0x9d, 0x6e, 0x15, 0x22, 0xe2, 0x52, 0x0f, 0x96, 0xbd, 0xb4, 0x5e,
	0xf6, 0x50, 0xdf, 0xa0, 0x08, 0xea, 0xa5, 0x94, 0x78, 0xf0, 0xb8, 0xcc, 0x36, 0x83, 0x2e, 0x62,
	0x52, 0x93, 0xa9, 0xc5, 0xb7, 0x97, 0xfc, 0x59, 0x51, 0xe8, 0x29, 0xf0, 0x4d, 0xe6, 0x9b, 0x99,
	0x1f, 0x8c, 0x5f, 0x91, 0x69, 0x8f, 0xdf, 0xd5, 0xd6, 0x1a, 0x36, 0xe2, 0x38, 0x3c, 0xe5, 0x25,
	0x5c, 0xbc, 0xd8, 0x96, 0x49, 0xd2, 0xc6, 0x58, 0x25, 0xc9, 0x6d, 0x8d, 0x76, 0x54, 0xd6, 0xff,
	0xb0, 0x93, 0xf4, 0xb9, 0x23, 0xc7, 0xe2, 0x06, 0x46, 0xad, 0x76, 0x8c, 0x7a, 0x43, 0x75, 0xab,
	0x8a, 0x6c, 0x9a, 0xcd, 0x73, 0x09, 0x1d, 0x7a, 0x52, 0x62, 0x06, 0x43, 0x1b, 0x5b, 0x8a, 0xde,
	0xb4, 0x3f, 0x1f, 0x2d, 0xc6, 0x71, 0x5c, 0x95, 0xfc, 0x5d, 0xb5, 0x5c, 0xc1, 0x20, 0x22, 0x31,
	0x83, 0x73, 0xe7, 0xf5, 0xde, 0xa9, 0x77, 0x1f, 0x0d, 0xd9, 0xa2, 0x17, 0xbc, 0x67, 0x1d, 0x5e,
	0x05, 0x2a, 0xae, 0xe1, 0x14, 0xbf, 0xac, 0xa9, 0x15, 0x32, 0x16, 0xfd, 0xf0, 0xe5, 0xc4, 0x83,
	0x7b, 0x64, 0x5c, 0x3c, 0xc3, 0xf0, 0x21, 0xde, 0x27, 0x1e, 0x21, 0xff, 0xbb, 0xbb, 0x98, 0xa4,
	0x15, 0x0e, 0x1c, 0x34, 0x39, 0x50, 0xfb, 0xcd, 0xe0, 0x68, 0x79, 0x0b, 0x57, 0x9a, 0x78, 0x6f,
	0xec, 0x7b, 0xd5, 0x90, 0x26, 0xe4, 0xb7, 0x2a, 0x85, 0xb8, 0xcc, 0xd3, 0xb4, 0xb5, 0x6f, 0x5f,
	0x67, 0xcd, 0x20, 0x78, 0xee, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x99, 0x0d, 0xf6, 0xa1, 0x66,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GatewayClient is the client API for Gateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GatewayClient interface {
	WriteRecords(ctx context.Context, in *WriteRecordsRequest, opts ...grpc.CallOption) (*WriteRecordResponse, error)
}

type gatewayClient struct {
	cc *grpc.ClientConn
}

func NewGatewayClient(cc *grpc.ClientConn) GatewayClient {
	return &gatewayClient{cc}
}

func (c *gatewayClient) WriteRecords(ctx context.Context, in *WriteRecordsRequest, opts ...grpc.CallOption) (*WriteRecordResponse, error) {
	out := new(WriteRecordResponse)
	err := c.cc.Invoke(ctx, "/proto.Gateway/WriteRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServer is the server API for Gateway service.
type GatewayServer interface {
	WriteRecords(context.Context, *WriteRecordsRequest) (*WriteRecordResponse, error)
}

func RegisterGatewayServer(s *grpc.Server, srv GatewayServer) {
	s.RegisterService(&_Gateway_serviceDesc, srv)
}

func _Gateway_WriteRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).WriteRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Gateway/WriteRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).WriteRecords(ctx, req.(*WriteRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Gateway",
	HandlerType: (*GatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteRecords",
			Handler:    _Gateway_WriteRecords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}
